### PR TITLE
[Web][8.0] Add 8.0 to TOC

### PR DESCRIPTION
**Pull request by pkosko**
The goal of this PR is to add missing 8.0 reference in doc page:
image

### CODE REVIEW

**Comment by pkosko** [comment]
Dear maintainers could you please verify if my change will affect TOC mentioned in PR description? Otherwise, how it could be achieved?

**Review by safir-srbd — COMMENTED** [review]
> Dear maintainers could you please verify if my change will affect TOC mentioned in PR description? Otherwise, how it could be achieved?

@pkosko From initial checking, it seems like it does get added from the dropdown but the LNB does not appear. For this I think it is best if you contact Ta Duc Huy (huy.td@samsung.com), the site manager of Tizen Docs.

To see how it appears here, visit this link: https://docs1.stg.tizen.org/staging/1931/application/web/api/8.0/device_api/mobile/index.html.

**Comment by sgchoi5** [comment]
> > Dear maintainers could you please verify if my change will affect TOC mentioned in PR description? Otherwise, how it could be achieved?
> 
> @pkosko From initial checking, it seems like it does get added from the dropdown but the LNB does not appear. For this I think it is best if you contact Ta Duc Huy ([huy.td@samsung.com](mailto:huy.td@samsung.com)), the site manager of Tizen Docs.
> 
> To see how it appears here, visit this link: https://docs1.stg.tizen.org/staging/1931/application/web/api/8.0/device_api/mobile/index.html.

I've send an email to Ta Duc Huy. He is not charge of Tizen site anymore. He will forward my question email to proper person.

**Comment by pkosko** [comment]
Hello, any updates on this topic?

**Comment by kimcinoo** [comment]
I found one part that needs to be modified while checking this issue. 
The following files have 7.0 information. Please update it.
```
./docs/application/web/api/8.0/device_api/mobile/index.xml
./docs/application/web/api/8.0/device_api/tv/index.xml
./docs/application/web/api/8.0/device_api/wearable/index.xml
```

**Comment by pkosko** [comment]
> ```
> ./docs/application/web/api/8.0/device_api/mobile/index.xml
> ./docs/application/web/api/8.0/device_api/tv/index.xml
> ./docs/application/web/api/8.0/device_api/wearable/index.xml
> ```

Thank you for notification about this - I've updated it.

**Comment by kimcinoo** [comment]
> ut this - I've updated it

We need to update our side as well. We will update with high priority. I apologize for any inconvenience.

**Comment by kimcinoo** [comment]
Please checkout the webpage https://docs1.stg.tizen.org/staging/1931

**Comment by pkosko** [comment]
> Please checkout the webpage https://docs1.stg.tizen.org/staging/1931

Hello, this staging looks as expected - https://docs1.stg.tizen.org/staging/1931/application/web/api/8.0/device_api/mobile/index.html

image

**Review by safir-srbd — APPROVED** [review]
> > Please checkout the webpage https://docs1.stg.tizen.org/staging/1931
> 
> Hello, this staging looks as expected - https://docs1.stg.tizen.org/staging/1931/application/web/api/8.0/device_api/mobile/index.html
> 
> image

@pkosko Since everything seems to be okay, I am approving this PR.

**Pull request merged**
