### PR TITLE
Adds newly removed module of Native API

### PR DESCRIPTION
**Pull request by sgchoi5**
Native Module : UI - UI View Manager will be removed since 7.0.
To notice it, I am going to update this page

### CODE REVIEW

**Comment by sgchoi5** [comment]
Looks good to me
https://docs1.stg.tizen.org/staging/1598/application/native/tutorials/details/native-removed-history/

**Comment by arisha-srbd** [comment]
Hello @sgchoi5. Hope you are doing well. I noticed that you made changes in a single line only as it will be removed since 7.0. I wanted to know if you want me to review the whole file, or check the modified part only.

**Comment by sgchoi5** [comment]
@arisha-srbd Hello, I am the maintainer of this page. If you review whole page and suggest some update, I will apply it. Thanks in advance.

**Review by arisha-srbd — COMMENTED** [review]
@sgchoi5 I have gone through the PR and it looks good. I have only one suggestion. Previously both title case and sentence case were accepted for 1st headings. However, after discussing with @mijin85cho and @asm-foysal, we have decided to fix one style for all 1st headings to maintain consistency throughout the web pages.

So my suggestion is to apply title case for the 1st heading of this PR.
_Line 1 suggestion:_ Removed Functions and Enumerations of Tizen Native API

**Comment by sgchoi5** [comment]
@arisha-srbd Thanks for your review. I've applied it.
https://docs1.stg.tizen.org/staging/1598/application/native/tutorials/details/native-removed-history/

**Review by sgchoi5 — COMMENTED** [review]
Looks good to me! plz, review changes

**Review by arisha-srbd — APPROVED** [review]
@sgchoi5 thank you for applying the changes. 

@asm-foysal @mijin85cho I am approving this PR for merging.

**Pull request merged**
