### PR TITLE
Correct a typo : Prrovides -> Provides

### PR DESCRIPTION
**Pull request by theojin**
### Change Description ###
Correct a typo.

### Bugs Fixed ###
There're no issues.
I've just found it.

### API Changes ###

No API changes.

### CODE REVIEW

**Comment by mijin85cho** [comment]
So many thanks for the fix @theojin.
However as the Native API files are generated by Native API team,
I think we should ask @sgchoi5 to check this issue also.

**Comment by mijin85cho** [comment]
Hello, @sgchoi5 
We got another report of a typo issue in Native API reference files.
Would you please check this, too?
Thanks in advance.

**Comment by sgchoi5** [comment]
Will be fixed for Mobile/Wearable 4.0/5.0/5.5 API Reference
by fixing media_doc.h directly.
plz, close this issue.

**Comment by mijin85cho** [comment]
Thanks for response @sgchoi5. I close this PR.

**Pull request closed without merging**
