### PR TITLE
Updated steps of creating app for TV

### PR DESCRIPTION
**Pull request by rishu-samsung**
Updated this document with new:
- Screenshots
- Writing content for the new type of TV web application process

### CODE REVIEW

**Comment by mijin85cho** [comment]
@rishu-samsung I think you should check your update yourself first, or ask your team member to check.

https://docs.stg.tizen.org/staging/694/application/web/get-started/tv/first-app is the result of your PR, and I hope you read this page first.

**Comment by rishu-samsung** [comment]
Hello @journey2w, Hello @mijin85cho,

This is not a final commit, there are still some more reviews and editing going on. Kindly wait for the final commit.

**Comment by mijin85cho** [comment]
Hello, @rishu-samsung 
I think you didn't check @journey2w's comment carefully.
The points she asked to fix were not fixed at all.
Would you please read @journey2w's comment before you update the PR?

**Comment by rishu-samsung** [comment]
As per @journey2w advice, I am closing this PR for now.

**Pull request closed without merging**
