### PR TITLE
[WIP] Add examples for new TAU 1.1 components 

### PR DESCRIPTION
**Pull request by lslachciak**
Added set of "Use example" buttons for new components in TAU 1.1

### CODE REVIEW

**Comment by lslachciak** [comment]
https://docs.stg.tizen.org/staging/940/application/web/api/5.5/ui_fw_api/Mobile_UIComponents/mobile_Coverflow.htm
https://docs.stg.tizen.org/staging/940/application/web/api/5.5/ui_fw_api/Mobile_UIComponents/mobile_Dimmer.htm
https://docs.stg.tizen.org/staging/940/application/web/api/5.5/ui_fw_api/Mobile_UIComponents/mobile_Graph.htm
https://docs.stg.tizen.org/staging/940/application/web/api/5.5/ui_fw_api/Mobile_UIComponents/mobile_Interactive3D.htm
https://docs.stg.tizen.org/staging/940/application/web/api/5.5/ui_fw_api/Wearable_UIComponents/wearable_Coverflow.htm
https://docs.stg.tizen.org/staging/940/application/web/api/5.5/ui_fw_api/Wearable_UIComponents/wearable_dimmer.htm
https://docs.stg.tizen.org/staging/940/application/web/api/5.5/ui_fw_api/Wearable_UIComponents/wearable_graph.htm
https://docs.stg.tizen.org/staging/940/application/web/api/5.5/ui_fw_api/Wearable_UIComponents/wearable_interactive3D.htm

**Comment by mijin85cho** [comment]
To rebuild the staging URL, I close and reopen this PR.

**Comment by singa2000** [comment]
We get the verification PASS.
Would you merge it, please?

**Comment by mijin85cho** [comment]
Question. I can't merge this PR as there are conflicted files.
Also, it looks like the some fixes in this file are duplicated with https://github.com/Samsung/tizen-docs/pull/959. Would you please check?

**Comment by lslachciak** [comment]
@mijin85cho @singa2000 I suggest merging https://github.com/Samsung/tizen-docs/pull/959/commits
and closing this PR. It already contains this commit and is up to date

**Comment by mijin85cho** [comment]
> @mijin85cho @singa2000 I suggest merging https://github.com/Samsung/tizen-docs/pull/959/commits
> and closing this PR. It already contains this commit and is up to date

I agree with your suggestion. 
The updates are included in #959, so when the issues of #959 are fixed, I think we can merge #959 and just close #940 and #938.

**Comment by mijin85cho** [comment]
> > @mijin85cho @singa2000 I suggest merging https://github.com/Samsung/tizen-docs/pull/959/commits
> > and closing this PR. It already contains this commit and is up to date
> 
> I agree with your suggestion.
> The updates are included in #959, so when the issues of #959 are fixed, I think we can merge #959 and just close #940 and #938.

https://github.com/Samsung/tizen-docs/pull/959 is merged. So I close this PR as we discussed.

**Pull request closed without merging**
