### PR TITLE
Add new 6.0 tv tcs

### PR DESCRIPTION
**Pull request by sgchoi5**

### CODE REVIEW

**Review by annie-samsung — APPROVED** [review]
Changes look good, hence approving

**Comment by annie-samsung** [comment]
@sgchoi5 do I need to review the spec (PDF), since it is a specification I am guessing it is already reviewed by someone else?

**Comment by sgchoi5** [comment]
> @sgchoi5 do I need to review the spec (PDF), since it is a specification I am guessing it is already reviewed by someone else?

Yes, it was already reviewed by SRPOL API part and Iot PM part

**Comment by annie-samsung** [comment]
> > @sgchoi5 do I need to review the spec (PDF), since it is a specification I am guessing it is already reviewed by someone else?
> 
> Yes, it was already reviewed by SRPOL API part and Iot PM part


@sgchoi5, thanks for responding. Since the PDF is previously reviewed I am not reviewing it.

**Pull request merged**
