### PR TITLE
Add ToC to wearable popup documentation

### PR DESCRIPTION
**Pull request by lslachciak**
[Issue] https://github.com/Samsung/TAU/issues/215
[Problem] Popup documentation doesn't contain ToC
[Solution] Added ToC

Signed-off-by: Lukasz Slachciak <l.slachciak@samsung.com>

### CODE REVIEW

**Comment by mijin85cho** [comment]
Hello, @lslachciak. 
When this PR is approved by one of your team member after check, I'll merge it.

By the way,
I found that ui_fw_api/Wearable_UIComponents/wearable_virtuallist.htm doesn't have the title "Table of Contents" also by the chance.
Would you please check that file, too?

**Comment by lslachciak** [comment]
@mijin85cho I noted that we are not following the same documentation schema in many places.
So I'm thinking about applying one template to all sites, but this should be done separately from this PR.
@TomaszLukawskiSam could you review this item?

**Comment by mijin85cho** [comment]
> @mijin85cho I noted that we are not following the same documentation schema in many places.
So I'm thinking about applying one template to all sites, but this should be done separately from this PR.

@lslachciak I agree. 
In this PR, "Add ToC to wearable popup documentation" , let's focus on wearable_popup.htm file only.

**Comment by mijin85cho** [comment]
Hello, @TomaszLukawskiSam 
As lslachciak requested, would you please review this PR?

**Pull request merged**
