### PR TITLE
Restore TAU documentation changes - links

### PR DESCRIPTION
**Pull request by lslachciak**
### Restore TAU documentation changes - links  ###
Restore reverted commits for TAU components documentation.
Links to code.tizen.org examples were restored.

Restore is done to prepare for proper testing.

### CODE REVIEW

**Comment by mijin85cho** [comment]
I close this PR and reopen it to build the staging link again.

**Comment by grzegorz-czajkowski** [comment]
@mijin80lee I have no permission to https://github.com/lslachciak/tizen-docs/tree/master_revert and can not add my patch to this branch.
How about merging this first and then I will prepare separate PR with my fix?

**Comment by mijin85cho** [comment]
@grzegorz-czajkowski I think it is also a good suggestion. 

However, As far as I know these links should be checked by verification team to be merged.
So I'm waiting @singa2000's confirmation that these links are verified.

Can you wait till @singa2000's notification of that and the merge which will be done at that time?

**Comment by grzegorz-czajkowski** [comment]
@mijin85cho sure. Let's wait for confirmation.

**Comment by mijin85cho** [comment]
> We passed the verification.
> Would you apply the PR, please?

With @singa2000's comment, I merge this PR.
Thanks for letting me know.

**Pull request merged**
