### PR TITLE
One UI image updates P2

### PR DESCRIPTION
**Pull request by nawab-samsung**
### Change Description ###
As part of the oneUI image updates:
Updated the following images in the following folders:

**Image: testing_your_app_on_gear4.png**
`docs/application/dotnet/tutorials/media/testing_your_app_on_gear4.png`
`docs/application/native/get-started/wearable-watch/media/testing_your_app_on_gear4.png`
`docs/application/native/get-started/wearable-watch/media/testing_your_app_on_gear4.png`
`docs/application/native/get-started/wearable-widget/media/testing_your_app_on_gear4.png`
`docs/application/native/get-started/wearable/media/testing_your_app_on_gear4.png`
`docs/application/web/get-started/wearable-watch/media/testing_your_app_on_gear4.png`
`docs/application/web/get-started/wearable-widget/media/testing_your_app_on_gear4.png`
`docs/application/web/get-started/wearable/media/testing_your_app_on_gear4.png`

 **Image: testing_your_app_on_gear6.png**
`docs/application/dotnet/tutorials/media/testing_your_app_on_gear6.png`
`docs/application/native/get-started/wearable-watch/media/testing_your_app_on_gear6.png`
`docs/application/native/get-started/wearable-widget/media/testing_your_app_on_gear6.png`
`docs/application/native/get-started/wearable/media/testing_your_app_on_gear6.png`
`docs/application/web/get-started/wearable-watch/media/testing_your_app_on_gear6.png`
`docs/application/web/get-started/wearable-widget/media/testing_your_app_on_gear6.png`
`docs/application/web/get-started/wearable/media/testing_your_app_on_gear6.png`

**Image: testing_your_app_on_gear7.png**
`docs/application/dotnet/tutorials/media/testing_your_app_on_gear7.png`
`docs/application/native/get-started/wearable-watch/media/testing_your_app_on_gear7.png`      
`docs/application/native/get-started/wearable-widget/media/testing_your_app_on_gear7.png`
`docs/application/native/get-started/wearable/media/testing_your_app_on_gear7.png`
`docs/application/web/get-started/wearable-watch/media/testing_your_app_on_gear7.png`
`docs/application/web/get-started/wearable-widget/media/testing_your_app_on_gear7.png`
`docs/application/web/get-started/wearable/media/testing_your_app_on_gear7.png`

### CODE REVIEW

**Comment by mijin85cho** [comment]
FYI: There are some duplicated files with #1244 

 - samsung_galaxy_watches.png
 - testing_your_app_on_gear1.png
 - testing_your_app_on_gear2.png 
 - testing_your_app_on_gear3.png

**Comment by nawab-samsung** [comment]
@mijin85cho thanks, will check and fix the image.

**Comment by nawab-samsung** [comment]
@mijin85cho Thanks.

- I have fixed the size of one image, it was slightly bigger than the other images. 

- I am not able to figure out the duplicates. 

  - #1246 will have few images which I have updated in #1247. 
  - You may need to pull a branch to see the changes. 

Also, I have replaced the files wherever I have updated the image, for instance: 
ert

There is less probability of duplicates but request you to please point me to the right thing if I am not understanding your concern.

**Comment by mijin85cho** [comment]
@nawab-samsung Would you please check the https://github.com/Samsung/tizen-docs/pull/1247/files?

I'm not sure with the file status, but it seems you should rebase the PR with the latest status.

According to https://github.com/Samsung/tizen-docs/pull/1247/files,
it seems previous merged PR history is included. I don't think you intended to update docs/application/dotnet/guides/nui/flexcontainer.md or else.


Also, as you can see in https://github.com/Samsung/tizen-docs/pull/1246/files and https://github.com/Samsung/tizen-docs/pull/1247/files,
the files fixed with #1246 are included at here also.
image

image

As you can see, for example dotnet/tutorials/media/testing_your_app_on_gear1.png  is updated in both 1246 and 1247.


Most of all, according to the description for this PR says you are going to update 22 files of testing_your_app_on_gear4.png, testing_your_app_on_gear6.png, and testing_your_app_on_gear7.png.
Please check https://github.com/Samsung/tizen-docs/pull/1247/files, as there are 63 updated files.

**Comment by nawab-samsung** [comment]
@mijin85cho thanks and sure I will check.

**Comment by nawab-samsung** [comment]
Refer to https://github.com/Samsung/tizen-docs/pull/1264

**Comment by nawab-samsung** [comment]
All the image updates for this PR are in PR #1264

**Pull request closed without merging**
