### PR TITLE
Add a guide for package archive info APIs

### PR DESCRIPTION
**Pull request by jeremy-jang**
Change-Id: I679e6150824014ca5a8a0adaf1ca313b3dd90131
Signed-off-by: Sangyoon Jang <jeremy.jang@samsung.com>

### CODE REVIEW

**Comment by journey2w** [comment]
@surbhig12 and @annie-samsung 

Please review English sentence.

**Comment by surbhig12** [comment]
I have reviewed and attached the file.
I have made minor language changes to maintain consistency. 
[package-manager.zip](https://github.com/Samsung/tizen-docs/files/2030884/package-manager.zip)

**Comment by jeremy-jang** [comment]
@surbhig12 , I fixed based on your review. Please review again.

**Comment by mijin85cho** [comment]
Sorry for the late response.

Hello, @surbhig12 
It looks like now gerund is not recommended as a sub section title.

However,
the last section title is "Monitoring Package Events", starting with a gerund,
while other titles start with a verb, "Retrieve". Is it ok?

Also, in the "Related Information" section,
"Tizen 2.4 and higher for mobile" and "Tizen 2.3.1 and higher for wearable" are changed into small letter.
As we can see these Dependency information is in capital letters in other pages.
Are you going to fix these whole pages, too, later?

**Comment by mijin85cho** [comment]
Hello, @surbhig12 

Would you please check my question?

```
Hello, @surbhig12
It looks like now gerund is not recommended as a sub section title.

However,
the last section title is "Monitoring Package Events", starting with a gerund,
while other titles start with a verb, "Retrieve". Is it ok?

Also, in the "Related Information" section,
"Tizen 2.4 and higher for mobile" and "Tizen 2.3.1 and higher for wearable" are changed into small letter.
As we can see these Dependency information is in capital letters in other pages.
Are you going to fix these whole pages, too, later?
```

Regards

**Comment by surbhig12** [comment]
Hello @mijin85cho,

Thank you for pointing the gerund information out. We can modify the title to  "Monitoring Package Events".

Regarding the "Related Information" section:
We will address all these inconsistencies later at one shot. For now we can go ahead and use capital to maintain consistency with  all other pages.

**Comment by mijin85cho** [comment]
Hello, @surbhig12.

Thanks for the answer. Yes, we can use "Monitoring Package Events" as the title.
However my point was about the consistency between the titles.

In package-manager.md reviewed by you, we have these sub titles

 - Prerequisites
 - Retrieve All Package Information
 - Retrieve Specific Package Information
 - Retrieve Package Information from Archives
 - Monitoring Package Events
 - Related Information

You changed 3 sub titles from gerund to verb, from "Retrieving" to "Retrieve",
while only keeping last sub title in gerund form, "Monitoring".

Was there a reason to keep "Monitoring" only in that form, while changing other sub titles?

**Comment by surbhig12** [comment]
@mijin85cho,

I am sorry, it was a miss from my end and even while replying. I have fixed it now.

It must be replaced to "Monitor Package Events".

Reasons: We avoid using gerund as while translating it creates confusion.

Thank you so much for correcting me and sorry for the confusion.

**Comment by mijin85cho** [comment]
@surbhig12 
Thanks for the confirming. With this fix and few more additional touch we can merge this PR.
When jeremy-jang updates the PR, please check it and approve it when you see no issue.

Hello, @jeremy-jang 
Would you please change "## Monitoring Package Events" in line 193 to "## Monitor Package Events"?

Also, please modify the spaces before the code line to array the layout.
As like below sample, From 
```
package_info_cb(package_info_h package_info, void *user_data)
{
```
to
```
   package_info_cb(package_info_h package_info, void *user_data)
   {
```
The additional spaces needed lines are below.
 - Add 3 spaces in from of the line **from line 48 to line 90**.
 - Add 3 spaces in from of the line **from line 92 to line 96**.
 - Add 1 space in from of the line **from line 104 to line 113**.
 - Add 1 space in from of the line **from line 148 to line 155**.
 - Add 3 spaces in from of the line **from line 188 to line 190**.

Thanks in advance

**Comment by jeremy-jang** [comment]
@surbhig12 
I made some fixes. Please review again.

**Comment by jeremy-jang** [comment]
@mijin85cho 
Done.

**Comment by mijin85cho** [comment]
Thanks for the review & update.

**Comment by mijin80lee** [comment]
TD Sync Completed.

**Pull request merged**
