### PR TITLE
Update supported macOS versions

### PR DESCRIPTION
**Pull request by adityaaswani**
### Change Description ###

Describe your changes here.

For instance,
 - Fix broken links of native application docs.
 -  ...

### Bugs Fixed ###

Provide links to bugs here

For instance,

 - Issue #265

### API Changes ###

In case of ACR, put the link of ACR

For instance,

 - ACR: ACR-1120

### CODE REVIEW

**Review by sangwook96 — APPROVED** [review]
Looks good to me!!

**Comment by mijin85cho** [comment]
Dear SRBD
Would you please review this PR, to be included when what is Tizen overview is update to docs.tizen.org?
According to the content, this PR seems to be included when Tizen Studio 4.6 release publish, but missed.

**Comment by mijin85cho** [comment]
Dear SRBD
Would you please review this PR, to be included when what is Tizen overview is update to docs.tizen.org?
According to the content, this PR seems to be included when Tizen Studio 4.6 release publish, but missed.

**Review by safir-srbd — APPROVED** [review]
@adityaaswani @mijin85cho Since there was a minor change in this PR, I've reviewed the changed part only. Since everything looks fine to me, I am approving this PR for merging.

**Pull request merged**
