### PR TITLE
Test

### PR DESCRIPTION
**Pull request by lehongha**
Test CI pull

### Change Description ###

Describe your changes here.

For instance,
 - Fix broken links of native application docs.
 -  ...

### Bugs Fixed ###

Provide links to bugs here

For instance,

 - Issue #265

### API Changes ###

In case of ACR, put the link of ACR

For instance,

 - ACR: ACR-1120

### CODE REVIEW

**Comment by mijin85cho** [comment]
I don't know why, but I can see so many test trials for the README.md file..

**Comment by lehongha** [comment]
Sorry @mijin85cho, I just created pull requests for testing auto-deploy when a pull request is created.
I will close the pull request after testing. Sorry for bothering you.

**Comment by huytaduc** [comment]
Just for testing Jenkins CI

**Comment by huytaduc** [comment]
checkout the webpage https://docs.tizen.org/staging/433

**Comment by huytaduc** [comment]
checkout the webpage https://docs.tizen.org/staging/433

**Comment by huytaduc** [comment]
checkout the webpage https://docs.stg.tizen.org/staging/433

**Pull request closed without merging**
