### PR TITLE
Screenshots for Project Wizard page of 5.5

### PR DESCRIPTION
**Pull request by rishu-samsung**
As per the request by Ms. Kang we have updated the Project Wizard page with screenshots with Tizen 5.5 names.

### CODE REVIEW

**Comment by rishu-samsung** [comment]
> We have to sync docs and TD.
> If you upload the files having the same file names others, they are overwritten.
> Please check the same image files and use them.

These are the updated screenshots with the same file name. These should overwrite the existing ones. Whereas I checked on the Developer site, screenshots are updated there at the same location. Please suggest what should we do with this PR.

**Comment by journey2w** [comment]
> > We have to sync docs and TD.
> > If you upload the files having the same file names others, they are overwritten.
> > Please check the same image files and use them.
> 
> These are the updated screenshots with the same file name. These should overwrite the existing ones. Whereas I checked on the Developer site, screenshots are updated there at the same location. Please suggest what should we do with this PR.

**Comment by rishu-samsung** [comment]
> docs/application/web/guides/media/tizen-3.0-native-web-api-modules.pdf is not related this PR.
> Maybe it is updated because of DRM in your PC.
> Please remove the pdf file in this PR.

Latest commit has four PNGs added and the PDF file is removed now.

**Comment by rishu-samsung** [comment]
As per @journey2w advice, I am closing this PR for now

**Pull request closed without merging**
