### PR TITLE
[NUI][TCSACR-409] Add guide for NUI Palette API

### PR DESCRIPTION
**Pull request by lwc0917**
### Change Description ###

Add guide for NUI Palette APIs

### Bugs Fixed ###

No bugs Fixed

### API Changes ###

- ACR: TCSACR-409

### CODE REVIEW

**Comment by lwc0917** [comment]
@annie-samsung  Thank you for your review.

The document has been revised according to the review content, and the target branch has been changed.

**Comment by annie-samsung** [comment]
@lwc0917, you missed to include the changes you had done to this file: docs/application/dotnet/guides/nui/overview.md

**Comment by lwc0917** [comment]
@annie-samsung 

Thank you for reviewing.

the master branch's overview.md file is totally different with 6.5_prepare branch's one.
So i thought it's not need to update.

Does it seem necessary to update only the palette-related content at overview.md?

**Comment by annie-samsung** [comment]
> @annie-samsung
> 
> Thank you for reviewing.
> 
> the master branch's overview.md file is totally different with 6.5_prepare branch's one.
> So i thought it's not need to update.
> 
> Does it seem necessary to update only the palette-related content at overview.md?

I agree, I think for now let's ignore overview.md

**Review by annie-samsung — APPROVED** [review]
Approving changes

**Pull request merged**
