### PR TITLE
Add 8.0 Native API Reference

### PR DESCRIPTION
**Pull request by sgchoi5**
Added 8.0 Native API Reference
Moved legacy reference to archive folder
-- Overview
-- 8.0
-- Archive
---Wearable
---Mobile
---Iot Headed
---Iot Headless

### CODE REVIEW

**Comment by sgchoi5** [comment]
Waiting for the support of doc server team (Native API folder restructuring)

**Comment by duchuyta** [comment]
Close, reopen to trigger build

**Comment by journey2w** [comment]
Please checkout the webpage https://docs1.stg.tizen.org/staging/1905

**Comment by journey2w** [comment]
Please checkout the webpage https://docs1.stg.tizen.org/staging/1905

**Comment by journey2w** [comment]
Please checkout the webpage https://docs1.stg.tizen.org/staging/1905

**Comment by sgchoi5** [comment]
LGTM

**Review by safir-srbd — DISMISSED** [review]

**Comment by sgchoi5** [comment]
OK. Operation server is ready. I've just got it from server team leader (SE / iljooo.kim@samsung.com)

**Review by safir-srbd — APPROVED** [review]
Server team confirmed. Will merge and push to live.

**Pull request merged**
