### PR TITLE
Add privilege guide in prerequisites section

### PR DESCRIPTION
**Pull request by yunmiha**
Signed-off-by: Yunmi Ha <yunmi.ha@samsung.com>

### Change Description ###

Describe your changes here.

For instance,
 - Add privilege guide in prerequisites section.
 -  ...

### Bugs Fixed ###

Provide links to bugs here

For instance,

 - N/A

### API Changes ###

In case of ACR, put the link of ACR

For instance,

 - N/A

### CODE REVIEW

**Comment by mijin85cho** [comment]
Please check the branch. Select one of the master or tizen_5.5_prepare

**Samsung:master** for Tizen 5.0
**Samsung:tizen_5.5_prepare** for Tizen 5.5

**Comment by yunmiha** [comment]
Need to merge both of them (Tizen 5.0 and Tizen 5.5).

**Comment by mijin85cho** [comment]
If it is applied to master branch, which is for Tizen 5.0,
you don't need to applied to tizen_5.5_prepare branch.
In the future, PRs in tizen_5.5_prepare will be merged into master keeping current and only applying Tizen 5.5 diff.

Please update the fix to master branch.

**Comment by mijin85cho** [comment]
We will review this update on https://github.com/Samsung/tizen-docs/pull/786.

**Pull request closed without merging**
