### PR TITLE
[ACR-1710] capi-media-streamrecorder module deprecated

### PR DESCRIPTION
**Pull request by hancepark**
Signed-off-by: hancepark <hance.park@samsung.com>

### Change Description ###

capi-media-streamrecorder is not used by any other module, so deprecating all the public API

### API Changes ###
 - ACR: ACR-1710
 - https://code.sec.samsung.net/jira/browse/ACR-1710

### CODE REVIEW

**Comment by hancepark** [comment]
Hello. 
Dealing with this this ACR has been delayed for a long time. If this become a issue, please let  me know. 
Thank you.

**Comment by omar-srbd** [comment]
Hello @hancepark, I hope you are well.

After an analysis of the topic file (application/native/guides/multimedia/stream-recorder.md) removed in this PR, I found two more instances in a single file (application/native/guides/index.md) where this file (application/native/guides/multimedia/stream-recorder.md) is mentioned.

The two instances are at **Line 129** and **Line 133** of **application/native/guides/index.md** file.
Please check the mentioned file and change/remove the **API submodule** description accordingly.

Thank you.

**Comment by hancepark** [comment]
Hello @omar-srbd, Appreciate for your review in detail.
I remove two instances that you mentioned. 
Please check new patch and let me know if other modification is needed. 

Thank you and have a nice weekend.

**Comment by omar-srbd** [comment]
LGTM
@hancepark, thanks for incorporating all the changes.

@asm-foysal @mijin85cho, I am approving this PR for merging.

**Review by omar-srbd — APPROVED** [review]
LGTM

**Pull request merged**
