### PR TITLE
Update file-system.md

### PR DESCRIPTION
**Pull request by almcken**
should be fileHandleWrite instead of fileHandleRead

### Change Description ###

Code had the wrong reference

For instance,
 - Fix broken links of native application docs.
 -  ...

### Bugs Fixed ###

Provide links to bugs here

For instance,

 - Issue #265

### API Changes ###

In case of ACR, put the link of ACR

For instance,

 - ACR: ACR-1120

### CODE REVIEW

**Review by omar-srbd — COMMENTED** [review]
Hello @almcken,
I have gone through the file in this PR. In addition to the corrections I have made to the file, I have noticed some errors where I was unable to comment.
I have listed all the problems along with their correction suggestions below:


1.	Line 3 – “**Note**”
Suggestion - “[!NOTE]”
Reference – For alerts, please use the alerts formatting as per guide.
https://github.com/Samsung/tizen-docs/blob/master/styleguide/custom-style.md#alerts-note-tip-important-caution-warning

2.	Line 10 – “The Filesystem API is mandatory for Tizen Mobile, Wearable, and TV profiles, which means that it is supported on all mobile, wearable, and TV devices. All mandatory APIs are supported on the Tizen emulators.”
Suggestion - “The Filesystem API is mandatory for Tizen Mobile, Wearable, and TV profiles, which means that it is supported on all mobile, wearable, and TV devices. All mandatory APIs are supported on Tizen emulators.”
Reference – For nouns such as tool names, it is recommended to not use "The"

3.	Line 30 – “File and Directory Access”
Suggestion - “File and directory access”
Reference – For second heading, please use sentence style capitalization
https://github.com/Samsung/tizen-docs/blob/master/styleguide/style.md#capitalization

4.	Line 36 – “**Note**”
Suggestion - “[!NOTE]”
Reference – For alerts, please use the alerts formatting as per guide.
https://github.com/Samsung/tizen-docs/blob/master/styleguide/custom-style.md#alerts-note-tip-important-caution-warning

5.	Line 49 – “Manage File Storages”
Suggestion - “Manage file storages”
Reference – For second heading, please use sentence style capitalization
https://github.com/Samsung/tizen-docs/blob/master/styleguide/style.md#capitalization

6.	Line 59 – “If the search is successful, the list of found `FileSystemStorage` objects (in [mobile](../../api/latest/device_api/mobile/tizen/filesystem.html#FileSystemStorage), [wearable](../../api/latest/device_api/wearable/tizen/filesystem.html#FileSystemStorage), and [TV](../../api/latest/device_api/tv/tizen/filesystem.html#FileSystemStorage) applications) is passed to the success event handler.”; 
“:” missed before code snippet.
Suggestion - “If the search is successful, the list of found `FileSystemStorage` objects (in [mobile](../../api/latest/device_api/mobile/tizen/filesystem.html#FileSystemStorage), [wearable](../../api/latest/device_api/wearable/tizen/filesystem.html#FileSystemStorage), and [TV](../../api/latest/device_api/tv/tizen/filesystem.html#FileSystemStorage) applications) is passed to the success event handler:”
Reference – Code snippets should be preceded by a “colon” 

7.	Line 78 – “The success callback receives the `FileSystemStorage` object containing the storage details as an input parameter.”; 
“:” missed before code snippet.
Suggestion - “The success callback receives the `FileSystemStorage` object containing the storage details as an input parameter:”
Reference – Code snippets should be preceded by a “colon”

8.	Line 92 – “An event is generated each time the storage state changes.”; 
“:” missed before code snippet.
Suggestion - “An event is generated each time the storage state changes:”
Reference – Code snippets should be preceded by a “colon”

9.	Line 107 – “To stop receiving the notifications, use the `removeStorageStateChangeListener()` method.”; 	
“:” missed before code snippet.
Suggestion - “To stop receiving the notifications, use the `removeStorageStateChangeListener()` method:”
Reference – Code snippets should be preceded by a “colon”
 
10.	Line 113 – “Create and Delete Directories”
Suggestion - “Create and delete directories”
Reference – For second heading, please use sentence style capitalization
https://github.com/Samsung/tizen-docs/blob/master/styleguide/style.md#capitalization

11.	Line 116 – “You can delete directories using `deleteDirectory()` method. Target pointed by the path specified will be deleted from the file system.”
“:” before the listing just to maintain consistency within the document.
Suggestion - “You can delete directories using `deleteDirectory()` method. Target pointed by the path specified will be deleted from the file system:”
Reference – An unordered list should be preceded by a “colon”

12.	Line 120 – “The directory is created, in destination pointed by `path` and successCallback function should be called. If directory can not be created for some reason, the errorCallback is called and error message can be logged.”; 	
“:” missed before code snippet.
Suggestion - “The directory is created, in destination pointed by `path` and successCallback function should be called. If directory can not be created for some reason, the errorCallback is called and error message can be logged:”
Reference – Code snippets should be preceded by a “colon”

13.	Line 135 – “The second parameter defines whether the deletion is performed recursively for the sub-directories as well. If the parameter is set to `false`, the directory is deleted only if it is empty.”; 	
“:” missed before code snippet.
Suggestion - “The second parameter defines whether the deletion is performed recursively for the sub-directories as well. If the parameter is set to `false`, the directory is deleted only if it is empty:”
Reference – Code snippets should be preceded by a “colon”

14.	Line 148 – “Delete Files”
Suggestion - “Delete files”
Reference – For second heading, please use sentence style capitalization
https://github.com/Samsung/tizen-docs/blob/master/styleguide/style.md#capitalization
 
15.	Line 166 – “Retrieve Files and File Details”
Suggestion - “Retrieve files and file details”
Reference – For second heading, please use sentence style capitalization
https://github.com/Samsung/tizen-docs/blob/master/styleguide/style.md#capitalization

16.	Line 168 – “You can retrieve a list of files or file URIs using the `listDirectory()` and `toURI()` methods. The URI can be used to identify the file, for example, by using it as the `src` attribute on an HTML `img` element.”
“:” before the listing just to maintain consistency within the document.
Suggestion - “You can retrieve a list of files or file URIs using the `listDirectory()` and `toURI()` methods. The URI can be used to identify the file, for example, by using it as the `src` attribute on an HTML `img` element:”
Reference – An unordered list should be preceded by a “colon”

17.	Line 170 – “To retrieve a list of all files and directories located in a specified directory, use the `listDirectory()` method of the `filesystem` object. The method returns an array of `DOMString` elements, each being a path with name of file inside a directory pointed by `path`.”; 	
“:” missed before code snippet.
Suggestion - “To retrieve a list of all files and directories located in a specified directory, use the `listDirectory()` method of the `filesystem` object. The method returns an array of `DOMString` elements, each being a path with name of file inside a directory pointed by `path`:”
Reference – Code snippets should be preceded by a “colon”
 
18.	Line 185 – “To retrieve the file URI, use the `toURI()` method.”; 	
“:” missed before code snippet.
Suggestion - “To retrieve the file URI, use the `toURI()` method:”
Reference – Code snippets should be preceded by a “colon”

19.	Line 202 – “Firstly, open a file using the `openFile()` function with the `mode` parameter allowing to read its contents.”; 	
“:” missed before code snippet.
Suggestion - “Firstly, open a file using the `openFile()` function with the `mode` parameter allowing to read its contents:”
Reference – Code snippets should be preceded by a “colon”

20.	Line 210 – ~~“Use readString() or readStringNonBlocking() to retrieve the file content as a DOMString.”;
Shouldn't “DOMString” be enclosed within code tags?~~ **(Comment is no longer relevant)**
“:” missed before code snippet.
Suggestion - “Use readString() or readStringNonBlocking() to retrieve the file content as a DOMString:”
Reference – Code snippets should be preceded by a “colon”

21.	Line 216 – “Use readData() or readDataNonBlocking() to retrieve the file content as a Uint8Array object (binary data).”; 
“:” missed before code snippet.
Suggestion - “Use readData() or readDataNonBlocking() to retrieve the file content as a Uint8Array object (binary data):”
Reference – Code snippets should be preceded by a “colon”

22.	Line 223 – “Use readBlob() or readBlobNonBlocking() to retrieve the file content as a Blob object.”; 
“:” missed before code snippet.
Suggestion - “Use readBlob() or readBlobNonBlocking() to retrieve the file content as a Blob object:”
Reference – Code snippets should be preceded by a “colon”
 
23.	Line 241 – “Close the file when it is not in use.”; 
“:” missed before code snippet.
Suggestion - “Close the file when it is not in use:”
Reference – Code snippets should be preceded by a “colon”

24.	Line 246 – “**Note**”
Suggestion - “[!NOTE]”
Reference – For alerts, please use the alerts formatting as per guide.
https://github.com/Samsung/tizen-docs/blob/master/styleguide/custom-style.md#alerts-note-tip-important-caution-warning

25.	Line 250 – “Manage Files and Directories”
Suggestion - “Manage files and directories”
Reference – For second heading, please use sentence style capitalization
https://github.com/Samsung/tizen-docs/blob/master/styleguide/style.md#capitalization

26.	Line 262 – “**Note**”
Suggestion - “[!NOTE]”
Reference – For alerts, please use the alerts formatting as per guide.
https://github.com/Samsung/tizen-docs/blob/master/styleguide/custom-style.md#alerts-note-tip-important-caution-warning

27.	Line 266 – “Perform all actual operations, such as reading, writing, or closing on the file through the `FileHandle` object based on a current position, which can be obtained or modified through calling `seek()` operation on `FileHandle` object.”; 
“:” missed before code snippet.
Suggestion - “Perform all actual operations, such as reading, writing, or closing on the file through the `FileHandle` object based on a current position, which can be obtained or modified through calling `seek()` operation on `FileHandle` object:”
Reference – Code snippets should be preceded by a “colon”
 
28.	Line 275 – “use writeString() or writeStringNonBlocking() to write `DOMString` to file.”; 
“:” missed before code snippet.
Suggestion - “use writeString() or writeStringNonBlocking() to write `DOMString` to file:”
Reference – Code snippets should be preceded by a “colon”

**The code snippets appearing between line 277 – 290 seems to be out of alignment from the preceding bullet points.**
Please check and confirm if this is ok or not.

29.	Line 281 – “use writeData() or writeDataNonBlocking() to write `Uint8Array` object contents to file.”; 
“:” missed before code snippet.
Suggestion - “use writeData() or writeDataNonBlocking() to write `Uint8Array` object contents to file:”
Reference – Code snippets should be preceded by a “colon”

30.	Line 287 – “use writeBlob() or writeBlobNonBlocking() to write `Blob` object contents to file.”; 
“:” missed before code snippet.
Suggestion - “use writeBlob() or writeBlobNonBlocking() to write `Blob` object contents to file:”
Reference – Code snippets should be preceded by a “colon”

31.	Line 370 – “Supported Virtual Roots”
Suggestion - “Supported virtual roots”
Reference – For second heading, please use sentence style capitalization
https://github.com/Samsung/tizen-docs/blob/master/styleguide/style.md#capitalization


32.	**This comment is no longer relevant.** ~~Line 383 – “| `ringtones` | Location for ringtones (read-only location).< br >**Note**< br >The `ringtones` virtual root is not supported on TV devices. |”
Suggestion - “| `ringtones` | Location for ringtones (read-only location).
[!NOTE]The `ringtones` virtual root is not supported on TV devices. |”
Reference – 
For alerts, please use the alerts formatting as per guide.
https://github.com/Samsung/tizen-docs/blob/master/styleguide/custom-style.md#alerts-note-tip-important-caution-warning
Please avoid using HTML tags in markdown file,
https://github.com/Samsung/tizen-docs/blob/master/styleguide/style.md#trailing-whitespace~~

33.	Line 385 – “| `wgt-package` | Location for storing Web application packages (read-only location). |”
Should the “web” be small case here?
Suggestion - “| `wgt-package` | Location for storing web application packages (read-only location). |”

34.	Line 386 – “| `wgt-private` | Location for the Web application private storage. |”
Should the “web” be small case here?
Suggestion - “| `wgt-private` | Location for the web application private storage. |”

35.	Line 387 – “| `wgt-private-tmp` | Location for the Web application private temporary storage. |”
Should the “web” be small case here?
Suggestion - “| `wgt-private-tmp` | Location for the web application private temporary storage. |”

36.	Line 390 – “Related Information”
Suggestion - “Related information”
Reference – For second heading, please use sentence style capitalization
https://github.com/Samsung/tizen-docs/blob/master/styleguide/style.md#capitalization

**Comment by mijin85cho** [comment]
Hello, @omar-srbd 

Thanks for the overall review and I hope to give you little comment : 

> Line 210 – “Use readString() or readStringNonBlocking() to retrieve the file content as a DOMString.”;
Shouldn't “DOMString” be enclosed within code tags?

I don't think DOMString needs code tag as it is a word used often outside of Tizen also.
**Reference :** https://www.google.com/search?q=DOMString&rlz=1C1GCEU_koKR821KR821&oq=DOMString&aqs=chrome..69i57j0i512j69i59j0i512l7.691j0j7&sourceid=chrome&ie=UTF-8

>Line 383 – “| ringtones | Location for ringtones (read-only location).< br >Note< br >The ringtones virtual root is not supported on TV devices. |”
Suggestion - “| ringtones | Location for ringtones (read-only location).
[!NOTE]The ringtones virtual root is not supported on TV devices. |”
Reference –
For alerts, please use the alerts formatting as per guide.
https://github.com/Samsung/tizen-docs/blob/master/styleguide/custom-style.md#alerts-note-tip-important-caution-warning
Please avoid using HTML tags in markdown file,
https://github.com/Samsung/tizen-docs/blob/master/styleguide/style.md#trailing-whitespace

Inside of a Table tag, the markdown tag doesn't work.
So inside of table tag, we can use html tag instead.
In the same reason, we can't use Note tag inside of table, so the Note is just written as "Note"

**Review by omar-srbd — COMMENTED** [review]
Hello @almcken,
This PR has been inactive for a while.
Could you please check and incorporate the suggested changes?

**Review by almcken — COMMENTED** [review]
Look great!

**Review by omar-srbd — COMMENTED** [review]
@almcken,
Thank you for the recent commits. However, it seems like the changes we suggested in the review comment were not addressed.
Please incorporate the suggested changes that were made in the previous review.
https://github.com/Samsung/tizen-docs/pull/1584#pullrequestreview-877265877

**Comment by almcken** [comment]
Sorry I don't have the time to fix everything. I just saw the one mistake and wanted to correct it for others.

**Pull request merged**
