### PR TITLE
Updates to Tizen 3.5 Release notes

### PR DESCRIPTION
**Pull request by kvbhat**
### Change Description ###

Describe your changes here.
- Removed redundant info from Known Issues as per review comments.

### Bugs Fixed ###

N/A

### API Changes ###

N/A

### CODE REVIEW

**Comment by kvbhat** [comment]
Changes compared to https://github.com/Samsung/tizen-docs/pull/890 are-
1) Remove Web Inspector Known issue as it is fixed.
2) Remove Native UI Builder from Known Issues as this is deprecated.
3) Remove Connection manager related text from "Web and Native IDE" Known Issues as this feature was replaced since Tizen Studio 2.0

Request to review and merge the same for Tizen Studio 3.5 Release.

**Comment by kvbhat** [comment]
Hi @journey2w 
This PR has all review changes requested in https://github.com/Samsung/tizen-docs/pull/890 we are unable to update the same as person who raised it is on leave (manishtr) and we dont have the creditials to push the same PR.
Mr.Oh mentioned that we need to update the release notes and push it by today.

As you can see in the commit history it has all the changes requested in PR 890 and additional changes as mentioned above as per review comments from Mr.ChangSeok Oh.

Request you to consider it this one time.

Thanks

**Comment by mijin85cho** [comment]
Hello, @kvbhat 
If so, would you please assign a person who can manage the PR till the end?
You asked to consider it one time,
but actually this PR is the 3rd PR for Tizen Studio 3.5 Release note.

1st. https://github.com/Samsung/tizen-docs/pull/845 	vivek-ellur
2nd. https://github.com/Samsung/tizen-docs/pull/890  manishtr 
3rd. https://github.com/Samsung/tizen-docs/pull/910 	kvbhat

As you are keeping closing and opening new PRs for every update,
it makes us hard to trace the update.

**Comment by kvbhat** [comment]
Hi @mijin85cho 
I understand and regret the inconvenience caused. 
Please consider this as final PR. 

Will assure that there will be no more new PR for Tizen Studio 3.5 Release note. 
Request you to consider this due to tight release deadline.

Regret the inconvenience. We will work to close the changes in this PR if you are ok with it.
Thanks for understanding.

**Comment by journey2w** [comment]
> Hi @journey2w
> This PR has all review changes requested in #890 we are unable to update the same as person who raised it is on leave (manishtr) and we dont have the creditials to push the same PR.
> Mr.Oh mentioned that we need to update the release notes and push it by today.
> 
> As you can see in the commit history it has all the changes requested in PR 890 and additional changes as mentioned above as per review comments from Mr.ChangSeok Oh.
> 
> Request you to consider it this one time.
> 
> Thanks

Why don't you use utility of Github?
I will consolidate your commits to PR #890. Please push a new comment on PR #890 when you want to update something.

**Comment by kvbhat** [comment]
Changes moved to https://github.com/Samsung/tizen-docs/pull/890
Thanks

**Pull request closed without merging**
