### PR TITLE
Add new Tizen TV TCS for 6.5

### PR DESCRIPTION
**Pull request by sgchoi5**
Added new Tizen TV 6.5 TCS pdf

### CODE REVIEW

**Comment by sgchoi5** [comment]
Looks good to me
https://docs1.stg.tizen.org/staging/1572/platform/compliance/compliance-specification/

**Comment by mijin85cho** [comment]
@asm-foysal Would you please review this PR and leave comments?

**Review by asm-foysal — COMMENTED** [review]
@mijin85cho hello! I've already checked out this PR and ensured that the link leads to the right pdf, do I have to review the entire pdf as well?

**Comment by mijin85cho** [comment]
> @mijin85cho hello! I've already checked out this PR and ensured that the link leads to the right pdf, do I have to review the entire pdf as well?

Reviewing entire PDF for the first time would take some time. I'd like to recommend you only check the updated part between tizen-6.0-compliance-specification-for-tv-profile-v1.0.1.pdf (existing one) and tizen-6.5-compliance-specification-for-tv-profile-v1.0.pdf (newly added one), if possible.

**Comment by sgchoi5** [comment]
Thanks for reviewing it. If you have any questions, you can contact Piotr Szydelko (p.szydelko@samsung.com) who is charge of TCS.

**Comment by sgchoi5** [comment]
Hello, @mijin85cho, @asm-foysal 
VD division is waiting for 6.5 TV tcs in docs.tizen.org. They already reviewed&approved PDF doc last week.
Could you approve PR?

If you suggest some changes for TCS, let us know them via Email. (p.szydelko@samsung.com and sunggyu.choi@samsung.com). We will update PDF.

**Review by asm-foysal — APPROVED** [review]
@sgchoi5 sorry about the delay, I'm approving this PR.

@mijin85cho I've checked the parts regarding Tizen 6.5 using the search tool as per Sagar suggestion, everything seems to be in order. I'll approve the PR for merging.

**Comment by mijin85cho** [comment]
> @sgchoi5 sorry about the delay, I'm approving this PR.
> 
> @mijin85cho I've checked the parts regarding Tizen 6.5 using the search tool as per Sagar suggestion, everything seems to be in order. I'll approve the PR for merging.

Thanks for the review, @asm-foysal Would you please also proceed merging? It seems good to me, too, and we are going to update docs.tizen.org end of this week.

**Pull request merged**
