### PR TITLE
Add internet connection state API details

### PR DESCRIPTION
**Pull request by prasadam-p**
[Native][Connection] Add internet connection state API details

 - ACR: http://suprem.sec.samsung.net/jira/browse/ACR-1452

### CODE REVIEW

**Comment by mijin85cho** [comment]
Hello, @prasadam-p 
I changed the working branch to master, as now Tizen 5.5 is published.
master branch is for the latest published version,
so for the further updates for Tizen 5.5, use master branch.

**Comment by n-chaprana** [comment]
> Hello, @prasadam-p
> I changed the working branch to master, as now Tizen 5.5 is published.
> master branch is for the latest published version,
> so for the further updates for Tizen 5.5, use master branch.

Hello @mijin85cho 
The change is already merged in master branch with https://github.com/Samsung/tizen-docs/pull/904.
We had a request in ACR to submit this change to tizen_5.5_prepare branch from Ms. Young-Ae Kang

**Comment by mijin85cho** [comment]
Hello, @n-chaprana 
Wasn't the #904 created to control http://suprem.sec.samsung.net/jira/browse/ACR-1452?

I can see the comment form Ms. Young-Ae Kang is created on 21/Oct, 
and the #904 is created on 23/Oct with same ACR number in the description.

>Signed-off-by: prashanth prasadam prasadam.p@samsung.com
>**Change Description**
>[ACR-1452] Add internet connection state API details in native connection documentation.


I guessed that #904 was created on wrong branch, master, while it should have been created on tizen_5.5_prepare at that time.
I merged the #904 anyway because at 28/Oct, the merged date of #904,
Tizen 5.5 published was quite near so disentangling the working branch didn't get big difference.

As you can see in #909, the updates in tizen_5.5_prepare are all merged into master now, 
and from that time we are not using tizen_5.5_prepare and considering master as the branch for Tizen 5.5.

If this fix is already applied on master anyway, you don't need to create another fix.
If I'm right, would you close this PR?

**Comment by n-chaprana** [comment]
Hello @mijin85cho 

Sure, I think the earlier PR should have been on tizen_5.5_release branch.
However this PR changes are already merged in master branch, so we will be closing this PR.

Thank you.

**Comment by prasadam-p** [comment]
Already merged on tizen_5.5_release branch, hence  closing this PR

**Pull request closed without merging**
