### PR TITLE
Add release notes for 5.6 release

### PR DESCRIPTION
**Pull request by adhavan-m**
### Change Description ###

Describe your changes here.

For instance,
 - Fix broken links of native application docs.
 -  ...

### Bugs Fixed ###

Provide links to bugs here

For instance,

 - Issue #265

### API Changes ###

In case of ACR, put the link of ACR

For instance,

 - ACR: ACR-1120

### CODE REVIEW

**Review by safir-srbd — COMMENTED** [review]
@adhavan-m Hello. Hope you are doing well. Before I start checking the document, I have one question. Was this PR pushed via a windows device or linux device?

Referencing https://github.com/Samsung/tizen-docs/pull/1701#discussion_r1006416851.

**Comment by adhavan-m** [comment]
> @adhavan-m Hello. Hope you are doing well. Before I start checking the document, I have one question. Was this PR pushed via a windows device or linux device?
> 
> Referencing [#1701 (comment)](https://github.com/Samsung/tizen-docs/pull/1701#discussion_r1006416851).

Hi @safir-srbd This pushed was pushed from a linux machine

**Review by safir-srbd — COMMENTED** [review]
@adhavan-m The Release Note looks fine to me, but you have missed out on one thing.

The release note should be added to the `toc_all.md` file, similar to #1877.

**Review by safir-srbd — APPROVED** [review]
@adhavan-m LGTM. I am approving this for merging.

**Pull request merged**
