### PR TITLE
[TV] Added bluetooth module

### PR DESCRIPTION
**Pull request by pkosko**
[ACR] https://code.sec.samsung.net/jira/browse/TWDAPI-253

### CODE REVIEW

**Comment by mijin85cho** [comment]
Hello, I have a question before I check the file in detail.

It looks like a new pages is added, 
so don't we need to update web/api/6.0/index.htm also?

As far as I remember  web/api/6.0/index.htm lists up every pages under device_api,
so it looks like index.htm should be updated also is a new page is added.

**Comment by pkosko** [comment]
The file docs/application/web/api/6.0/device_api/tv/index.html is also changed in this pull requests. Bluetooth module is included in index also.

**Comment by mijin85cho** [comment]
> The file docs/application/web/api/6.0/device_api/tv/index.html is also changed in this pull requests. Bluetooth module is included in index also.

Thanks for checking @pkosko.
How about /api/6.0/device_api/tv/index.xml file?

**Comment by pkosko** [comment]
@mijin85cho I think now all needed index files are updated:
* docs/application/web/api/6.0/device_api/tv/index.html
* docs/application/web/api/6.0/device_api/tv/index.xml 
*  docs/application/web/api/6.0/index.htm
Thank you for your review.

**Pull request merged**
