### PR TITLE
[ACR-1567][widget-viewer-dali] delete document for widget-viewer-dali

### PR DESCRIPTION
**Pull request by tscholb**
widget-viewer-dali will be deprecated.
so this document also need to deprecated.

### Change Description ###

Describe your changes here.

For instance,
 - Fix broken links of native application docs.
 -  ...

### Bugs Fixed ###

Provide links to bugs here

For instance,

 - Issue #265

### API Changes ###

In case of ACR, put the link of ACR

For instance,

 - ACR: ACR-1120

### CODE REVIEW

**Comment by mijin85cho** [comment]
Hello, @tscholb 
Thanks for the modification.

With this update, I can see the native/guides/applications/media/dali_widget_application.png image is also not in use now.

Would you please remove that image, too?

**Comment by mijin85cho** [comment]
Question. When I checked https://code.sec.samsung.net/jira/browse/ACR-1567, I could see this fix is for Tizen 6.0.

Would you please confirm this fix is for Tizen 6.0?
For now the fix is made on master branch, which is to handle Tizen 5.5.

If this fix is for Tizen 6.0, we should change the working branch to tizen_6.0_prepare.
I can try to change the working branch, so please confirm the target Tizen version.

**Comment by tscholb** [comment]
> Question. When I checked https://code.sec.samsung.net/jira/browse/ACR-1567, I could see this fix is for Tizen 6.0.
> 
> Would you please confirm this fix is for Tizen 6.0?
> For now the fix is made on master branch, which is to handle Tizen 5.5.
> 
> If this fix is for Tizen 6.0, we should change the working branch to tizen_6.0_prepare.
> I can try to change the working branch, so please confirm the target Tizen version.

Yes, this fix is for tizen 6.0. please change branch if it is possible

**Comment by mijin85cho** [comment]
> > Question. When I checked https://code.sec.samsung.net/jira/browse/ACR-1567, I could see this fix is for Tizen 6.0.
> > Would you please confirm this fix is for Tizen 6.0?
> > For now the fix is made on master branch, which is to handle Tizen 5.5.
> > If this fix is for Tizen 6.0, we should change the working branch to tizen_6.0_prepare.
> > I can try to change the working branch, so please confirm the target Tizen version.
> 
> Yes, this fix is for tizen 6.0. please change branch if it is possible

I changed the branch and it seems the branch is based on old history.
Would you please rebase it?

**Comment by tscholb** [comment]
> > > Question. When I checked https://code.sec.samsung.net/jira/browse/ACR-1567, I could see this fix is for Tizen 6.0.
> > > Would you please confirm this fix is for Tizen 6.0?
> > > For now the fix is made on master branch, which is to handle Tizen 5.5.
> > > If this fix is for Tizen 6.0, we should change the working branch to tizen_6.0_prepare.
> > > I can try to change the working branch, so please confirm the target Tizen version.
> > 
> > 
> > Yes, this fix is for tizen 6.0. please change branch if it is possible
> 
> I changed the branch and it seems the branch is based on old history.
> Would you please rebase it?

i think my base is master so it makes problem. so i updated this patch base on 6.0
could you check this?
https://github.com/Samsung/tizen-docs/pull/1171

if it is okay, i think this patch need to discard

**Comment by mijin85cho** [comment]
>i think my base is master so it makes problem. so i updated this patch base on 6.0
could you check this?
#1171
>
>if it is okay, i think this patch need to discard

Thanks for the new PR. 1171 is merged, so I close this PR.

**Pull request closed without merging**
