### PR TITLE
Merge from branch dev-remove-toc-file to branch master

### PR DESCRIPTION
**Pull request by haivutuan93**
### Change Description ###

Describe your changes here.

For instance,
 - Fix broken links of native application docs.
 -  ...

### Bugs Fixed ###

Provide links to bugs here

For instance,

 - Issue #265

### API Changes ###

In case of ACR, put the link of ACR

For instance,

 - ACR: ACR-1120

### CODE REVIEW

**Comment by huytaduc** [comment]
checkout the webpage https://docs.stg.tizen.org/staging/490

**Comment by haivutuan93** [comment]
Please review and merge branch of php dev team

**Comment by iljooo** [comment]
Dear @journey2w 
For deploying to production server, we need to apply this updates.
Please check and review in contents side.

Thanks.

**Comment by huytaduc** [comment]
checkout the webpage https://docs.stg.tizen.org/staging/490

**Comment by huytaduc** [comment]
checkout the webpage https://docs.stg.tizen.org/staging/490

**Comment by huytaduc** [comment]
checkout the webpage https://docs.stg.tizen.org/staging/490

**Comment by haivutuan93** [comment]
Dear Mr.Kim and Ms.Kang,
Please check merge commit

**Comment by huytaduc** [comment]
checkout the webpage https://docs.stg.tizen.org/staging/490

**Comment by journey2w** [comment]
@hai.vt
I'd like to close this PR because you seems to finish testing this PR.
I didn't remove dev-remove-toc-file branch so you can reopen this PR and get the latest commit on dev-remove-toc-file branch anytime you want.
Thanks.

**Pull request closed without merging**
