### PR TITLE
Filling gaps in the "return value" section.

### PR DESCRIPTION
**Pull request by lslachciak**
[Problem] Some methods did not have a "return section" in their description.
[Solution] Add missing sections.

### CODE REVIEW

**Comment by huytaduc** [comment]
checkout the webpage https://docs.stg.tizen.org/staging/593

**Comment by mijin85cho** [comment]
Just a question. While reviewing other PRs, too, I got you are separating sample codes into HTML and JS. Don't you need to separate the sample codes in these files, too?

**Comment by TomaszLukawskiSam** [comment]
> Just a question. While reviewing other PRs, too, I got you are separating sample codes into HTML and JS. Don't you need to separate the sample codes in these files, too?

@mijin85cho 
You are right.

@dorlinski 
Could you separate this code for JS and HTML. Thank you.

**Comment by dorlinski** [comment]
> > Just a question. While reviewing other PRs, too, I got you are separating sample codes into HTML and JS. Don't you need to separate the sample codes in these files, too?
> 
> @mijin85cho
> You are right.
> 
> @dorlinski
> Could you separate this code for JS and HTML. Thank you.

Done

**Comment by mijin85cho** [comment]
@TomaszLukawskiSam, would you please recheck the approved, but updated PRs like this?
There are some PRs about TAU, which were updated after approved.

**Comment by mijin85cho** [comment]
Merge conflict happend. Please resolve the conflicts to merge it.

**Comment by dorlinski** [comment]
Here is a new PR https://github.com/Samsung/tizen-docs/pull/634
You can close this one.

**Comment by lslachciak** [comment]
Changes in this PR are included in #634

**Pull request closed without merging**
