### PR TITLE
Update Common Application Controls page to remove profile concept

### PR DESCRIPTION
**Pull request by sgchoi5**
- Updated sentences related with profile, because profile concept is not available since 8.0

### CODE REVIEW

**Comment by sgchoi5** [comment]
Native: https://docs1.stg.tizen.org/staging/1936/application/native/guides/app-management/common-appcontrols/
Web: https://docs1.stg.tizen.org/staging/1936/application/web/guides/app-management/common-appcontrols/

**Comment by sgchoi5** [comment]
plz, wait for internal decision, not yet ready

**Review by pjh9216 — APPROVED** [review]
LGTM

**Comment by sgchoi5** [comment]
Got approval from PM part and Application Framework part

**Review by safir-srbd — APPROVED** [review]
@sgchoi5 Is this good for merging, from my review everything seems to be in order. Please do let me know, I am approving this PR for merging.

**Comment by sgchoi5** [comment]
@safir-srbd ready for merge. thanks for your review.

**Pull request merged**
