### PR TITLE
[5.5] Change TD URLs in Web api files to Docs.tizen.org URLs

### PR DESCRIPTION
**Pull request by mijin85cho**
Signed-off-by: Mijin, Cho <mijin85.cho@samsung.com>

### Change Description ###

To prepare moving to docs.tizen.org, I changed the TD urls in 5.5 Web API files to docs.tizen.org urls.

reference : 
- https://github.com/Samsung/tizen-docs/pull/610
- https://github.com/Samsung/tizen-docs/pull/643

### CODE REVIEW

**Comment by mijin85cho** [comment]
@pkosko I updated the links to follow "/application/web/..." form and removed ".md"s  at the end of each links.

The biggest reason of broken link was the filename extension, ".md", as on the docs site ".md"s are removed to create each page URL.

**example**
- file name : .../application/web/guides/personal/account.md
- page url : .../application/web/guides/personal/account

You can check the with below actual links
 - file : https://github.com/Samsung/tizen-docs/blob/master/docs/application/web/guides/personal/account.md
 - ulr : https://docs.tizen.org/application/web/guides/personal/account

If I removed ".md"s at previous commit, the link would have worked anyway.
However I changed to absolute link (only after the /application/.. is enough) with Ms. Kang's suggestion.

Also because of the difficulty of the managing links, Ms. Kang suggested to remove these links as one of the solution. While reading the API reference, how many times it will happen to go up to head of the page and get the link to guide page was her doubt. I'm also thinking about this.. What would be the efficient way about the links?

**Comment by pkosko** [comment]
@mijin85cho  I checked web docs about removal of all references to guides, but the result for me is clear - they are a meaning part of API reference and points the place where additional information can be found. In my opinion almost half of the links are part of more complex description, not only "See <developer.tizen.org>.html". Many important remarks need to be removed together with links.
For me, removing the links is not acceptable from API user convenience perspective. I think that we need maintain these links.

**Comment by lslachciak** [comment]
@mijin85cho in this PR I see changes for 5.5 documentation, shouldn't we change urls for older versions also?

**Comment by mijin85cho** [comment]
@lslachciak as we didn't fix how to control the links yet, I just updated 5.5 only to check the behavior with testing label.
When we choose the way, I'll check other versions, also.

@pkosko I see. Thanks for your opinion. I'll talk with Ms. Kang about it more.

**Comment by mijin85cho** [comment]
@pkosko Thanks for the PR update.
I added some more link update to your work with device_api for all version. The files didn't managed by you are updated now. 
I'll merge this PR with journey2w's approval. After merging this PR, the updates in web api files will be applied to docs.tizen.org only. Please refer that.

**Comment by mijin85cho** [comment]
@pkosko As there is an update request from you (https://github.com/Samsung/tizen-docs/pull/928#discussion_r345590764), would you please approve or merge this PR?

**Comment by pkosko** [comment]
> @pkosko As there is an update request from you ([#928 (comment)](https://github.com/Samsung/tizen-docs/pull/928#discussion_r345590764)), would you please approve or merge this PR?
I already marked this comment as resolved before. Now I also added the approve on this PR, as you requested.

**Comment by mijin85cho** [comment]
@pkosko Thanks for the response.

**Pull request merged**
