### PR TITLE
[Web API] Fix typing/spelling mistakes in notifications API

### PR DESCRIPTION
**Pull request by m-bialek**
Apply changes from #1622 to all versions.

### Change Description ###

 - fix typing/spelling mistakes (missing articles, missing commas, etc.)

### Bugs Fixed ###

N/A

### API Changes ###

N/A

### CODE REVIEW

**Review by safir-srbd — COMMENTED** [review]
@m-bialek Hi. Hope you are doing well!

All the changes you made look fine from my end, but I found one small issue at the end of all the pages (including the 7.0 pages that you edited in #1601 and #1622).

At the end of the pages, in between the Related Feature and Full WebIDL sections, there is no gap or space, as you can see in this screenshot below. Please add a space in between the two sections for all the notification pages if possible.

image

**Comment by m-bialek** [comment]
Hi @safir-srbd! It looks to me more like a CSS problem. I checked HTMLs and the PRs did not change those parts. This issue occurs also on [the official site](https://docs.tizen.org/application/web/api/6.5/device_api/mobile/tizen/notification.html#full-webidl).

**Comment by safir-srbd** [comment]
> Hi @safir-srbd! It looks to me more like a CSS problem. I checked HTMLs and the PRs did not change those parts. This issue occurs also on [the official site](https://docs.tizen.org/application/web/api/6.5/device_api/mobile/tizen/notification.html#full-webidl).

@m-bialek Thank you for your quick response.

I meant to say that this is a problem that was present from before the edits were made in the PR. I believe adding a space before the line where the 'Full WebIDL' heading begins should fix it. Would it be possible to make that change?

**Comment by m-bialek** [comment]
@safir-srbd 
I experimented a little and unfortunately it is not so easy. I guess I would need to change the templates which are used to generate HTMLs. I am not supposed to do it though.

**Comment by pkosko** [comment]
@safir-srbd template for HTML generations are same since tizen 2.3. Adding a space before Full WebIDL will cause to regenerate whole documentation and apply it to all versions of API - it will be a modification of over 400 files for just adding a space. I think that it will be reasonable to just leave it as is, what do you think?

**Review by safir-srbd — APPROVED** [review]
> @safir-srbd I experimented a little and unfortunately it is not so easy. I guess I would need to change the templates which are used to generate HTMLs. I am not supposed to do it though.

> @safir-srbd template for HTML generations are same since tizen 2.3. Adding a space before Full WebIDL will cause to regenerate whole documentation and apply it to all versions of API - it will be a modification of over 900 files (rough estimation for all modules for all profiles for all versions) for just adding a space. I think that it will be reasonable to just leave it as is, what do you think?

@m-bialek @pkosko If that's the case, then it is completely fine. Thank you both for your prompt replies. Everything else looks okay as well.

@asm-foysal @mijin85cho I am approving this PR for merging.

**Pull request merged**
