### PR TITLE
Add 7.0 Native API reference for mobile/wearable/iot

### PR DESCRIPTION
**Pull request by sgchoi5**
Added 7.0 Mobile API Reference
Added 7.0 Wearable API Reference
Added 7.0 Iot-Headed API Reference
Added 7.0 Iot-Headless API Reference

### CODE REVIEW

**Comment by journey2w** [comment]
To generate stg rutl, I'd like to close this PR and reopen it.

**Comment by safir-srbd** [comment]
@sgchoi5 Hello. Hope you are doing well.

Thank you for adding the Native API Reference files for Mobile, Wearable, and IoT. 

While going through the staging site for this PR, I found that in the `docs/application/native/api/overview.md` file ([staging link](https://docs1.stg.tizen.org/staging/1717/application/native/api/overview/)), the _Versions_ section has not been updated to include the links to the 7.0 index for each profile (Mobile, Wearable, IoT Headed, IoT Headless). I believe the links to 7.0 should be added to reflect the changes made in this PR.

**Comment by sgchoi5** [comment]
@safir-srbd Hello, thanks for your comments. I've updated overview.md.

**Comment by journey2w** [comment]
@sgchoi5 
Please check the following file:
https://docs1.stg.tizen.org/staging/1717/application/native/api/iot-headless/7.0/group__CAPI__SYSTEM__RESOURCE__MONITOR__MODULE.html

It seems that there is no group or it doesn't follow the module naming rule.

`Nodes.xml`:
```
          <Name>CAPI_SYSTEM_RESOURCE_MONITOR_MODULE</Name>
```

**Comment by sgchoi5** [comment]
Missed one header file including group definition. fixed it!

**Comment by sgchoi5** [comment]
Fixed group problem

**Review by safir-srbd — APPROVED** [review]
@asm-foysal @mijin85cho I am approving this PR for merging.

**Pull request merged**
