### PR TITLE
[base-utils] Add guides for immutable index module

### PR DESCRIPTION
**Pull request by lu-pik**
Added guide for immutable index module from base-utils library.

[ACR] http://suprem.sec.samsung.net/jira/browse/ACR-1118

Signed-off-by: Lukasz Pik <lu.pik@samsung.com>

### CODE REVIEW

**Comment by mijin85cho** [comment]
Hello, @annie-samsung. 
This is reminder of review request for this PR. Would you please assign a person to this PR?

@ To the person who will review this PR.
Hello, when you review this PR, also please check the layout of added lines.
It looks like the spaces in front of the lines are not arranged well, 
so the list items get tangled.
(ex. 2 spaces in line 2131. It should be 3 spaces)

image

**Comment by mijin85cho** [comment]
Hello, @annie-samsung 
This comment to remind you of this PR.
Would you please assign a person to this PR?

**Comment by Reni-90** [comment]
The file is reviewed and updated. 
Please find the updated file attached:
[i18n.zip](https://github.com/Samsung/tizen-docs/files/2159077/i18n.zip)

Please verify and let me know if any changes required.

Suggestions:
In line 2162: 
To maintain consistency throughout the document, rephrased: Destroy the index when it's no longer needed
to
Destroy the index when it is no longer needed
Actually, we can rephrase as:
Destroy the index when it is no longer required
or
Destroy the index when not in use

In line 2100:
Rephrased to: From Tizen 5.0, you can use immutable index API (in mobile and wearable applications) to create an immutable index, a thread-safe version of an alphabetic index without data records.

Actually, the content is a repetition from line 422. In my opinion, no value added to the document. If you agree, please rephrase it as:
From Tizen 5.0, you can use immutable index API (in mobile and wearable applications) to create an immutable index.

**Comment by lu-pik** [comment]
In line 2162, I stay with "Destroy the index when it is no longer needed" version.
In line 2100, stayed with original version, because sentence "From Tizen 5.0, you can use immutable index API (in mobile and wearable applications) to create an immutable index." makes no sense to me.

**Comment by mijin85cho** [comment]
Hello, @lu-pik. 

Thanks for the update.
Would you please fix some minor things more?

Please add 3 more spaces to in front of each code block lines, to fix layout.

 - from line 2106 to line 2109
 - from line 2115 to line 2118
 - from line 2124 to line 2127
 - from line 2131 to line 2136
 - from line 2140 to line 2149
 - from line 2153 to line 2158

@Reni-90 
Please check the updated result and approve this PR when you see no more issues.

**Comment by mijin85cho** [comment]
Hi, @Reni-90
As lu-pik updated PR, I'm waiting your approval now. I'll merge this PR and prepare to apply on Tizen Developer Site with your approval.

**Comment by mijin80lee** [comment]
TD Sync Completed.(for Tizen_5.0_prepare)

**Pull request merged**
