### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by krzydyn**
### Change Description ###

- Fixed typos in libteec API documantation.

### CODE REVIEW

**Comment by huytaduc** [comment]
checkout the webpage https://docs.stg.tizen.org/staging/548

**Comment by mijin85cho** [comment]
Please check "parameteres" on line 1134, too.

**Comment by huytaduc** [comment]
checkout the webpage https://docs.stg.tizen.org/staging/548

**Comment by huytaduc** [comment]
checkout the webpage https://docs.stg.tizen.org/staging/548

**Pull request merged**
