### PR TITLE
Deprecate Activity & Gesture Recognition

### PR DESCRIPTION
**Pull request by pvschakradhar**
Deprecating Activity & Gesture Recognition files because capi-context-motion is deprecated
ACR: ACR-1588 (https://code.sec.samsung.net/jira/browse/ACR-1588)

### CODE REVIEW

**Comment by annie-samsung** [comment]
@ pvschakradhar, I understand that this PR is about removing two files: Activity and Gesture Recognition
What about other documents (if any) linking to these documents? Those documents need to be identified and links need to be removed. 

@mijin85cho, thoughts?

**Comment by mijin85cho** [comment]
> @ pvschakradhar, I understand that this PR is about removing two files: Activity and Gesture Recognition
> What about other documents (if any) linking to these documents? Those documents need to be identified and links need to be removed.
> 
> @mijin85cho, thoughts?

To remove a page, we should check the links also for the case that other page has a hyperlink to the removed page.

For example, the application/native/guides/index.md and application/native/guides/location-sensors/overview.md pages have links to removed pages, 
so these links should be removed also. Otherwise we'll get broken links.

**Comment by annie-samsung** [comment]
@pvschakradhar could you please check on the above points

**Comment by mijin85cho** [comment]
Thanks for updating.

However, if there were inserted images in the deleted page and the images are not used in other pages, would you please remove the images also?
For example in gesture.md, there are 7 images. As these images are not is use now, they should be removed also.

@annie-samsung I hope you consider this point also.

**Review by annie-samsung — APPROVED** [review]
Checked for dependencies, no other files seem to be impacted. Hence approving.

**Pull request merged**
