### PR TITLE
Content revamp and suggestions for Overview page

### PR DESCRIPTION
**Pull request by divyk**
## Content Revamp for Tizen Studio pages

**Technical Sign off** by Tizen SDK team (Meeting held for the same and approved for publishing) 
 
Phase 1: This is revamped page for the Tizen studio index page  
Phase 2: Adding image  to the page which refers to other landing pages

Final proposed output in this page: See the attached image.
 
image

These are our suggestions based on our limited knowledge, please review.

With Regards, 
Divya & Nawab

### CODE REVIEW

**Comment by divyk** [comment]
@journey2w , @mijin85cho , request you to review and give your valuable suggestions.

**Comment by mijin85cho** [comment]
@divyk I think you'd better check your update result by yourself first.
You should check https://docs.stg.tizen.org/staging/711/application/tizen-studio/index or https://github.com/Samsung/tizen-docs/blob/e0432f6f92991458bd3053067b9896495ee1d95b/docs/application/tizen-studio/index.md, which is expected result of your PR.
Or, asking peer review to other SRI-B reviewer first would be good too.

**Comment by nawab-samsung** [comment]
Will re-raise the PR with attached image

**Comment by mijin85cho** [comment]
For reference. If you want to update the PR (fix the contents, adding images, etc), you can use `git commit --amend`

In the work space

1. fix the contents (update contents, fix markdown tags, etc..)
2. use `git add` to add the updated files.
3. `git commit -a --amend`
   With this, you can update the commit you made.
4. git push origin _your_working_branch_ **-f**
   This will forcibly update your commit in your repository, also this related PR.

With this commands, you don't need to close your PR and create new PR every time to apply a fix.
You can **update** these PRs.

**Pull request closed without merging**
