### PR TITLE
[ACR-1708] Remove 'media streamer' guide

### PR DESCRIPTION
**Pull request by jiyong2**
### API Changes ###

 - ACR: ACR-1708
Remove 'media streamer' guide

### CODE REVIEW

**Comment by jiyong2** [comment]
I deleted only the 'media streamer' item from 'docs/application/native/guides/index.md'.
I don't know why many broken links occur.
Please let me know if there is anything to do.

**Review by safir-srbd — COMMENTED** [review]
@jiyong2 Hello. Hope you are doing well!

I have a question regarding the deprecation of 'media streamer'.

I have found that you have removed the mention of 'media streamer' and other associated things from most md files.

But mentions of media streamer and associated APIs are present in a few API files such as `‎docs/iot/api/4.0/tizen-iot-headed/group__CAPI__MEDIA__FRAMEWORK.html`,`‎docs/iot/api/5.0/tizen-iot-headed/group__CAPI__MEDIA__STREAMER__MODULE.html`, and other API files. Should these be removed as well or is it okay to keep these files in case of a deprecation?

**Comment by jiyong2** [comment]
@safir-srbd Hello. Thank you for your checking.
API files are the API description of the old versions(4.0, 5.0, 5.5, 6.0, and 6.5).
The 'media streamer' API has been deprecated since 7.0, so it is right to maintain the old version.
Fortunately, there is no link to the guide in API files, so there is no problem in API files even if the guide is deleted.

**Comment by jiyong2** [comment]
@safir-srbd 
In addition, other deprecated APIs also keep the API files of old versions.

**Comment by safir-srbd** [comment]
@jiyong2 Thank you for the reply. 

I will check the PR accordingly then.

**Review by safir-srbd — APPROVED** [review]
@jiyong2 Everything looks alright to me. 

@asm-foysal @mijin85cho I am approving this PR for merging.

**Pull request merged**
