### PR TITLE
[ACR-1319]Add external storage feature

### PR DESCRIPTION
**Pull request by prjung**
Signed-off-by: pr.jung <pr.jung@samsung.com>

### Change Description ###
Add external storage feature

### Bugs Fixed ###
N/A

### API Changes ###
ACR-1319

### CODE REVIEW

**Comment by huytaduc** [comment]
checkout the webpage https://docs.stg.tizen.org/staging/579

**Comment by mijin85cho** [comment]
This PR is update version of https://github.com/Samsung/tizen-docs/pull/567.
So I assigned @divyk as a reviewer, as @divyk was doing the review of #567

**Comment by mijin85cho** [comment]
So many thanks for the update and review.

I think we have only one query left.

In the web/tutorials/app-filtering.md, would you please check the "Table: Available requirements for TV Web Device APIs"?
It is said this feature is supported by TV, too, 
so I wonder whether it should be added to the TV list, too.

If we don't need to add at that table, I'll merge this PR.

**Comment by prjung** [comment]
I updated we/tutorials/app-filtering.md.
Please check my new commit.
Thank you.

**Comment by huytaduc** [comment]
checkout the webpage https://docs.stg.tizen.org/staging/579

**Comment by mijin85cho** [comment]
I changed the branch from master to tizen_5.5_prepare as it is related with 5.5, however it looks like we need to rebase it.
Would you please rebase the PR?

**Comment by huytaduc** [comment]
checkout the webpage https://docs.stg.tizen.org/staging/579

**Comment by huytaduc** [comment]
checkout the webpage https://docs.stg.tizen.org/staging/579

**Pull request closed without merging**
