### PR TITLE
Update Mobile/Wearabe/Headed/Headless 5.0 / 5.5 / 6.0 Native API ref

### PR DESCRIPTION
**Pull request by sgchoi5**
Doc Issue List: Not yet fixed all issues.
https://code.sec.samsung.net/confluence/pages/viewpage.action?pageId=194846376

I've create PR for patches of last week.

### CODE REVIEW

**Comment by mijin85cho** [comment]
Hello, @sgchoi5 
With the PR I could compare the files with the previous files.
I checked the updates and got below questions.

- Would you please check again the updated files in Native 6.0 mobile?
   Lots of pages were removed and I'm not sure with this update. The removed pages for 6.0 mobile are remained in test server for 6.0 mobile.
   I'm doubting the case of iot-headless files are overwritten to Mobile 6.0.


- In below pages, while adding "Since" information, descriptions were removed.
   **updated :** 
   - https://docs1.stg.tizen.org/staging/1371/application/native/api/iot-headed/6.0/group__Elm__Tooltips.html#ga70fd5c066b8f07e3b42605a16a015cce
   - https://docs1.stg.tizen.org/staging/1371/application/native/api/iot-headed/6.0/group__Evas__Image.html#ga70cff757cad7f9e3a0be8557704c7d78
   image

   **previous example:** 
   - https://docs.tizen.org/application/native/api/iot-headed/5.0/group__Elm__Tooltips.html#ga70fd5c066b8f07e3b42605a16a015cce
   image


- Would you please check the menu tree of below page?
   https://docs1.stg.tizen.org/staging/1371/application/native/api/iot-headless/5.0/group__CAPI__UIX__MULTI__ASSISTANT__MODULE.html
   image

- With the updates, layout is dragged down under the LNB in some pages, comparing to the original page.
   As the previous pages looks fine, I think the updates should be checked again.
   https://docs1.stg.tizen.org/staging/1371/application/native/api/mobile/5.5/classDali_1_1AlphaFunction.html
   https://docs1.stg.tizen.org/staging/1371/application/native/api/mobile/5.5/struct__Ecore__Con__Event__Server__Add.html
   https://docs1.stg.tizen.org/staging/1371/application/native/api/mobile/5.5/struct__Ecore__Con__Event__Url__Progress.html
   https://docs1.stg.tizen.org/staging/1371/application/native/api/mobile/5.5/structdata__control__provider__sql__cb.html



Would you please check these questions and reply?

**Comment by sgchoi5** [comment]
1) Fixed 6.0 Mobile API ref. I think.. zipping wrong folder.... probably, sorry..
2) Fixed 5.0 Headless API ref. 
3) Added new EFL issue to this page. No. 62
   https://code.sec.samsung.net/confluence/pages/viewpage.action?pageId=194846376
4) Fixed 5.5 Mobile API ref. I think.. there was some problem when zipping files or unzipping files.. hm...

**Comment by mijin85cho** [comment]
In some pages in 6.0 Native Mobile, the link to the features are added back.
Would you please check?

For example
**Original :** https://docs.tizen.org/application/native/api/mobile/6.0/group__CAPI__GEOFENCE__MODULE.html
image

**Updated ;** https://docs1.stg.tizen.org/staging/1371/application/native/api/mobile/6.0/group__CAPI__GEOFENCE__MODULE.html
image

**Comment by mijin85cho** [comment]
Further issue checking is needed. So I close this PR waiting next update.

**Pull request closed without merging**
