### PR TITLE
Add attach_panel feature

### PR DESCRIPTION
**Pull request by hallower**
Add attach_panel feature due to this ACR(http://suprem.sec.samsung.net/jira/browse/ACR-1126).
I got a request from Ms. Kang to add new features to these files.
- docs/application/native/tutorials/details/app-filtering.md 
- docs/application/native/guides/device/system.md

But app-filtering.md is already modified with adding the new feature due to another ACR(http://suprem.sec.samsung.net/jira/browse/TCSACR-131).
So I modified system.md only for  that.
Thank you.

### CODE REVIEW

**Comment by mijin85cho** [comment]
Hello, Annie. Would you please check the updated point by hallower? To me the sentence looks good, so if you agree I'll just merge this PR.

**Comment by hallower** [comment]
Dear @annie-samsung,
Would you review this pull request?

**Comment by varunishg** [comment]
**Line #4**
This API helps you query system information keys to access various information about fixed platform features or device capabilities. It also lists out the supported features.

**Line #25** 
The table has 'Feature keys' in bold but 'System Keys' is not. Either keep both in bold or both in regular.
Another suggestion is to keep two separate tables. 

**Line #43**
Some device-specific information keys appear similar to feature keys used for application filtering, but their usage is different. Feature keys for device-specific information are used to determine whether the feature is supported in the system. Feature keys for application filtering let the Tizen Store filter the applications based on its features.

**Line #47**
You must include the <system_info.h> header file in your application, to use the functions and data types of the System Information API (in mobile and wearable applications).

**Line #56**
Device-specific information consists of a "key, value" pair. Use the `http://tizen.org/system/model_name` key with the data type-specific get function, to get the device model name.

**Line # 242**
Rephrase the paragraph: "If the device does not provide a built-in keyboard, the platform returns an empty string for this key and returns false for the http://tizen.org/feature/input.keyboard key."
to
Else, it returns an empty string for this key and returns false for the http://tizen.org/feature/input.keyboard key."

**Line # 650**
In the given table, the sentence 'The platform returns the maximum sound volume level' should be rephrased as 'The platform returns the maximum volume level'.

**Comment by mijin85cho** [comment]
Hello, varunishg.

As I asked to Annie, please focus on **updated point**, from line 131 to line 139.
It looks like you have no issue for the attach panel table added,
so I'll merge this PR regarding as it is approved by you.

Thanks

**Comment by mijin80lee** [comment]
TD Sync Completed.(for Tizen_5.0_prepare)

**Pull request merged**
