### PR TITLE
Change the graphics-and-ui.md file for tizen 5.5

### PR DESCRIPTION
**Pull request by schanlim**
### Change Description ###

Change the graphics-and-ui.md file for tizen 5.5
 - Change the TBM porting guide
 - Change the TDM porting guide
 - Change the TPL-EGL porting guide

### CODE REVIEW

**Comment by journey2w** [comment]
@schanlim 
Does this change is for Tizen 5.5? 
I will change the branch to tizen_5.5_prepare.
Thanks.

**Comment by schanlim** [comment]
> @schanlim
> Does this change is for Tizen 5.5?
Yes it is for Tizen 5.5 and the latest version of the tizen.

> I will change the branch to tizen_5.5_prepare.
> BTW, please resolve the conflict first.
How can I resolve the conflicts? I only see the message below.
**"This branch has conflicts that must be resolved.
Only those with write access to this repository can merge pull requests"**

> Thanks.

**Comment by journey2w** [comment]
> > @schanlim
> > Does this change is for Tizen 5.5?
> > I will change the branch to tizen_5.5_prepare.
> > BTW, please resolve the conflict first.
> > Thanks.
> 
> Yes it is for Tizen 5.5 and the latest version of the tizen.
> 
> How can I resolve the conflicts? I only see the message below.
> **"This branch has conflicts that must be resolved. Only those with write access to this repository can merge pull requests"**

You can resolve conflict with the following commands in your local PC:

git checkout -b backup (back up the current branch)
git remote add upstream https://github.com/Samsung/tizen-docs
git fetch upstream
git checkout tizen_5.5_prepare
git merge upstream/tizen_5.5_prepare tizen_5.5_prepare
git cherry-pick 1df9c093f99b9f72731cdbb66c1d0359c42cd1ed
git cherry-pick 463612b5fea20538ce620bd52dfb78092245e2ae
git cherry-pick 5b1221c004151ec3f8b73a14fe1cfcb31affeae6
git branch -D master (To keep the current PR)
git checkout -b master

It is so complex. I can do it for you.

**Comment by schanlim** [comment]
I will make the new PR again.

Thank you very much.

**Pull request closed without merging**
