### PR TITLE
Move feature 'http://tizen.org/feature/multimedia.stream_recorder'

### PR DESCRIPTION
**Pull request by hancepark**
Feature added to Mobile & Wearable
: 'http://tizen.org/feature/multimedia.stream_recorder'

And mediastorage and externalstorage privilege is added.
Signed-off-by: Hyunsoo Park hance.park@samsung.com

Change Description
Describe your changes here.
-New feature is added like above.

### CODE REVIEW

**Comment by mijin85cho** [comment]
Question.

This PR is same fix  with https://github.com/Samsung/tizen-docs/pull/1089, but working on tizen_6.0_prepare branch.

I just doubt the PR update mistake for https://github.com/Samsung/tizen-docs/pull/1089, 
so want to ask you check once again before processing it.

According to https://code.sec.samsung.net/jira/browse/ACR-1506, 
Tizen 5.5 is the correct version. 
Would you please check this PR again?

**Note** : tizen_6.0_prepare branch will be merged into master branch when Tizen 6.0 is published.
So if you updated master branch, you don't need to update tizen_6.0_prepare branch for the same fix.
If Tizen 6.0 is published, from that time master branch will manage tizen 6.0 document.

**Comment by hancepark** [comment]
Hello. 
Thank you for comments:)
I also wonder about that point, but in ACR below, Young-Ae Kang request to apply it on this branch
(https://code.sec.samsung.net/jira/browse/TCSACR-305).

If i understand wrong, please let me know. Thank you

**Comment by hancepark** [comment]
Dear All, Please handle this ACR patch

**Comment by mijin85cho** [comment]
> Hello.
> Thank you for comments:)
> I also wonder about that point, but in ACR below, Young-Ae Kang request to apply it on this branch
> (https://code.sec.samsung.net/jira/browse/TCSACR-305).
> 
> If i understand wrong, please let me know. Thank you

Hello, @hancepark 
Thanks for your comment.

I check the comment in the link, 
and it looks like the update on tizen_6.0_prepare branch is requested **in case of** "new features for Tizen 6.0".


```
...

repo: https://github.com/Samsung/tizen-docs

branch: master

file: docs/application/dotnet/guides/multimedia/stream-recorder.md 

...

Lastly, If there are new features for multimedia on Tizen 6.0, please add new features in the app-filtering.md on tizen_6.0_prepare branch.

```

So if we don't have any new feature for Tizen 6.0, I think the PR to master branch would be enough.
Would you please let me know your opinion?

**Comment by hancepark** [comment]
Oh, i see. 
It is new feature from 5.5.
So, we don't have to apply this patch!
I understand :)

**Comment by hancepark** [comment]
So i want to close this PR if you agree :)

**Comment by mijin85cho** [comment]
Thanks for the checking, @hancepark.
With your confirmation, I close this PR.

**Pull request closed without merging**
