### PR TITLE
Update Tizen Compliance Tests information

### PR DESCRIPTION
**Pull request by jihun87park**
### Change Description ###
To release 6.0 TCT
- Add Csharp TCT information
- Correct Web TCT information

### CODE REVIEW

**Comment by journey2w** [comment]
@annie-samsung
This commit is for Tizen 6.0.
Please make the priority of this PR up
Thanks.

**Review by nawab-samsung — CHANGES_REQUESTED** [review]
@jihun87park I have given the first set of comments, request you to incorporate the same. Following which I will do a review again. 

Thanks.

**Comment by nawab-samsung** [comment]
@jihun87park request you to kindly incorporate the comments.

Thanks

**Comment by nawab-samsung** [comment]
@jihun87park 
 Gentle reminder: request you to kindly incorporate the comments.
Thanks

**Comment by nawab-samsung** [comment]
@jihun87park
Gentle reminder: request you to kindly incorporate the comments.
Thanks

**Comment by nawab-samsung** [comment]
@jihun87park
Gentle reminder: request you to kindly incorporate the comments.
Thanks

**Comment by nawab-samsung** [comment]
I have reviewed the PR couple of days ago, but there is no update as such. 
@jihun87park request you to kindly do the needful. 

Thanks

**Comment by nawab-samsung** [comment]
@jihun87park Gentle reminder: request you to kindly incorporate the comments.

Thanks

**Comment by nawab-samsung** [comment]
@jihun87park Gentle reminder: request you to kindly incorporate the comments.
@annie-samsung  it has been so long, that this PR is pending, as there is no response from the author.

**Comment by nawab-samsung** [comment]
@mijin85cho  I have given multiple reminders on this PR. Can you please let me know how should we proceed ?

**Comment by nawab-samsung** [comment]
I had pinged the developer over chat also, but no response.

**Comment by annie-samsung** [comment]
@jihun87park this PR has been pending for a while now, if it is not required anymore can we close this PR?

**Comment by annie-samsung** [comment]
Closing this PR as no response from the developer even after multiple reminders.

**Pull request closed without merging**
