### PR TITLE
Update 7.0 Native API Reference

### PR DESCRIPTION
**Pull request by sgchoi5**
Updated 7.0 Native API Reference (Mobile/Wearable/Headed/Headless)
Main goal: updated small description of voice control and others.
Sub goal: add missing html files of EFL (Mobile only)

* No need to review all files

### CODE REVIEW

**Comment by sgchoi5** [comment]
Looks good to me.
https://docs1.stg.tizen.org/staging/1749/application/native/api/mobile/7.0/group__CAPI__UIX__VOICE__CONTROL__MODULE.html

**Comment by safir-srbd** [comment]
@sgchoi5 Hello! Hope you are well.

From the description and your comments, the main changes you made are related to the EFL section under UI in Mobile API, and some changes to voice control. Other than that, are there any other files or sections that you think should be reviewed?

**Comment by sgchoi5** [comment]
@safir-srbd Hello, No need to review the content of Native API Reference. : )

**Review by safir-srbd — APPROVED** [review]
@sgchoi5 Considering the number of files in this PR, I couldn't check each and every change made. But I went through the major changes described in the Change Description, and browsed through the API pages as well. Everything seems to be in order.

@asm-foysal @mijin85cho I am approving this PR for merging.

**Pull request merged**
