### PR TITLE
Update TV 6.5 TCS to fix .NET version

### PR DESCRIPTION
**Pull request by sgchoi5**
1) Fixed wrong version number
2.3.2. Tizen .NET API Categories
 .NET Standard API 2.0 => .NET Standard API **2.1**

2) Modified a sentence to use more proper term.
  2.11. .NET Runtime
TV device implementations MUST support all mandatory requirements of .NET Core Runtime version 3.1 or newer.
=>
TV device implementations MUST support .netcore 3.1 API specification.

Plz, review only changed content.

### CODE REVIEW

**Comment by sgchoi5** [comment]
https://docs1.stg.tizen.org/staging/1628/platform/compliance/compliance-specification/
L.G.T.M

**Comment by safir-srbd** [comment]
@sgchoi5 Hi. Hope you are well. I have gone through the changes that you have made. Just one question.

> 2. Modified a sentence to use more proper term.
>    2.11. .NET Runtime
>    TV device implementations MUST support all mandatory requirements of .NET Core Runtime version 3.1 or newer.
>    =>
>    TV device implementations MUST support .netcore 3.1 API specification.

Is '.netcore' a proper way of spelling it, or should it be '.NET Core'?

**Comment by sgchoi5** [comment]
TV device implementations MUST support .netcore 3.1 API specification.  => I got this yesterday from .NET runtime part leader: Mr. Cho (ws77.cho@samsung.com). He said it is more correct and proper than previous.

**Review by safir-srbd — APPROVED** [review]
@sgchoi5 I have reviewed the updated parts of the PDF as you said, and everything looks fine to me.

@mijin85cho I am approving this PR for merging.

**Pull request merged**
