### PR TITLE
update LNB

### PR DESCRIPTION
**Pull request by dkson95**
Signed-off-by: Dongkyun Son <dongkyun.s@samsung.com>

### Change Description ###

Left Navigation Bar Modification:
image

### CODE REVIEW

**Comment by sangwook96** [comment]
AS-IS
Get Started
.NET Application
Web Application
Native Application
=> SDK 메뉴가 아니라 플랫폼에서 작성한 부분이 많은것 같아서 ,변경을 할려면 해 파트와 논의가 필요할수 있을것  같습니다.

TO-BE
Common-Tool 
툴이라는 것이 저희 SDK 파트가 가지는 툴을 이야기 하는거인지 ? 
커몬툴이라고하면 SDK 가지는 툴이 아니고 범위가 다양할것 같습니다.(;;)

문서를 변경할려는 것이 SDK 를 통해서 타이젠 앱 개발시 TS 보다 VS/VSCode 가 알리기 위함인것 같은데
그렇다면
https://docs.tizen.org/ 에 TizenStudio 대신에 VS/VSCode 를 간락히 업데이트 하거나 링크 하는것도 방법이지 않을까 합니다.

**Comment by mijin85cho** [comment]
Hello, @asm-foysal 
We are going to restructure the LNB, to highlight Visual Studio / Visual Studio Code, and to tone down the Tizen Studio.

During the restructuring, some basic tools from Tizen Studio are categorized with name "Common Tools", 
but not sure with the name whether if it is proper.

(In above comment, @sangwook96 is also worrying : "Common Tools sounds like more broad notion to use to SDK")

We still need to have some communication how to emphasize  Visual Studio / Visual Studio and de-emphasize,
so please check PR and share us your opinion too.

**Comment by dkson95** [comment]
> Hello, @asm-foysal We are going to restructure the LNB, to highlight Visual Studio / Visual Studio Code, and to tone down the Tizen Studio.
> 
> During the restructuring, some basic tools from Tizen Studio are categorized with name "Common Tools", but not sure with the name whether if it is proper.
> 
> (In above comment, @sangwook96 is also worrying : "Common Tools sounds like more broad notion to use to SDK")
> 
> We still need to have some communication how to emphasize Visual Studio / Visual Studio and de-emphasize, so please check PR and share us your opinion too.

@mijin85cho Thank you for the review with arrangement 👍 
@asm-foysal could you review the slide and share your idea on the approach ? I hope the overall documents could be improved to provide better experience thanks to you.

[Tizen Document Renewal.pptx](https://github.com/Samsung/tizen-docs/files/8045705/Tizen.Document.Renewal.pptx)

**Review by mijin85cho — COMMENTED** [review]
>**Note**
> This comment is to the suggestion in this PR.
> As how to emphasize the VS / VS code is not fixed yet,
> this PR is one way of suggestions, which means it is not fixed yet to follow this way.

After checking the diff, we suggest below structure.
For detailed description, I add links in the comment.

**Suggestion :**

**\# Get Started**

**\# .NET Application** : [reference comment](https://github.com/Samsung/tizen-docs/pull/1586#discussion_r804448870)

\## \[Overview](/application/dotnet/index.md)
\## \[Learn about .NET](/application/dotnet/learn-about-dotnet.md)

\## Get Started
\### \[Overview](/application/dotnet/get-started/index.md)
\### \[Create .NET Application](/application/dotnet/get-started/first-app.md) : [reference comment](https://github.com/Samsung/tizen-docs/pull/1586#discussion_r804463132)
...

**\# Web Application**

\## \[Overview](/application/web/index.md)

\## Get Started with VSCode
\### \[Web application development](/application/vscode-ext/Tizen/web_app.md)

\## Get Started with VS
\### \[Web application development](/application/vstools/Tizen/web.md)

\## Get Started with Tizen Studio : [reference comment](https://github.com/Samsung/tizen-docs/pull/1586#discussion_r804497544)
\### \[Overview](/application/web/get-started/overview.md)
...


**\# Native Application** 

\## \[Overview](/application/native/index.md)

\## Get Started using VSCode
\### \[Native application development](/application/vscode-ext/Tizen/native.md)

\## Get Started using VS
\### \[Native application development](/application/vstools/Tizen/native.md)

\## Get Started with Tizen Studio : [reference comment](https://github.com/Samsung/tizen-docs/pull/1586#discussion_r804497544)
\### \[Overview](/application/native/get-started/overview.md)
...


**\# Tizen Tools Family** //This is a tentative name
\## Visual Studio Tools for Tizen
\## Visual Studio Code Extension for Tizen
\## Tizen Studio
\## Common Tools : [reference comment](https://github.com/Samsung/tizen-docs/pull/1586#discussion_r804499558)

**Comment by dkson95** [comment]
@mijin85cho Thank you for suggestion for each 👍 
@asm-foysal Would you help to revise according to Mr.Cho's comment or it would be appreciated if you can create another PR for the duplicated info. reduction including https://github.com/Samsung/tizen-docs/pull/1586#issuecomment-1035851981.

Thank you!

**Comment by mijin85cho** [comment]
Hello, @asm-foysal Any thought or suggestion?

**Comment by dkson95** [comment]
let's keep to proceed on https://github.com/Samsung/tizen-docs/pull/1590

@mijin85cho @asm-foysal 
thank you for this consideration!

**Pull request closed without merging**
