### PR TITLE
Update TAU 5.5 documentation with changes from 5.0

### PR DESCRIPTION
**Pull request by pkaczmarczy**
Pages for NumberPicker, TimePicker and DatePicker
widgets were missing in TAU 5.5 documentation.
TAU 5.5 documentation did not have updated
formatting rules and screens.

### CODE REVIEW

**Comment by lslachciak** [comment]
PR seems OK, unfortunatelly can't access 
https://jenkins-docs.stg.tizen.org/job/STG_docs_PR_builder/1150/
to see what is wrong

**Comment by mijin85cho** [comment]
Hello, @huytaduc 
Would you please check this build fail?

**Comment by mijin85cho** [comment]
@lslachciak If you're ok, I'll just merge this PR as you approved it.

**Comment by lslachciak** [comment]
I'm OK.
We approved 5.0 changes in separet PR, This is just 5.5 update with 5.0 content

**Pull request merged**
