### PR TITLE
Update 8.0 Native API Ref for new 2 modules

### PR DESCRIPTION
**Pull request by sgchoi5**
- Added webauthn//key manager(client extended)  to 8.0 Native API Ref
- Fixed minor patched for typo
* No need to be reviewed by doc team. API part already checked the output.

### CODE REVIEW

**Comment by sgchoi5** [comment]
https://docs1.stg.tizen.org/staging/1996 is not accessible. Is there any issues?

**Comment by safir-srbd** [comment]
> https://docs1.stg.tizen.org/staging/1996 is not accessible. Is there any issues?

@sgchoi5 I will contact the site manager and see what can be done. 

Thanks for highlighting this issue.

**Comment by safir-srbd** [comment]
> > https://docs1.stg.tizen.org/staging/1996 is not accessible. Is there any issues?
> 
> @sgchoi5 I will contact the site manager and see what can be done.
> 
> Thanks for highlighting this issue.

@sgchoi5 The site should be accessible now.

**Comment by sgchoi5** [comment]
Looks good to me.
webauthn: https://docs1.stg.tizen.org/staging/1996/application/native/api/common/8.0/group__CAPI__WEBAUTHN__MODULE.html
key Manager Extended: https://docs1.stg.tizen.org/staging/1996/application/native/api/common/8.0/group__CAPI__KEY__MANAGER__CLIENT__EXTENDED__MODULE.html

**Review by safir-srbd — APPROVED** [review]
@sgchoi5 LGTM! I am approving this PR for merging

**Pull request merged**
