### PR TITLE
Fix wrong privilege level information

### PR DESCRIPTION
**Pull request by myroot**
### Change Description ###
 Fix wrong privilege level information in NFC guide

http://tizen.org/privilege/nfc.admin
this privilege level is platform level on Native and .Net Application

### Bugs Fixed ###
https://github.com/Samsung/TizenFX/issues/462

### API Changes ###
None

### CODE REVIEW

**Comment by huytaduc** [comment]
checkout the webpage https://docs.stg.tizen.org/staging/478

**Comment by myroot** [comment]
> 
> 
> checkout the webpage https://docs.stg.tizen.org/staging/478


403
Page Forbidden

**Comment by mijin85cho** [comment]
> checkout the webpage https://docs.stg.tizen.org/staging/478

This is automatic message, to give a test page for the update which is not working now.

Your fix is merged and applied on Tizen Developer Site, https://developer.tizen.org/development/guides/.net-application/connectivity-and-wireless/nfc.

**Comment by mijin80lee** [comment]
TD Sync Completed.(cross-check)

**Pull request merged**
