### PR TITLE
Update 8.0 Native API Reference for doc enhancement

### PR DESCRIPTION
**Pull request by sgchoi5**
- Update 8.0 Native API Reference
- No need to be reviewed by doc part (API / ACR part have checked)

### CODE REVIEW

**Comment by sgchoi5** [comment]
L.G.T.M
https://docs1.stg.tizen.org/staging/2021/application/native/api/common/8.0/

**Comment by sgchoi5** [comment]
Fixed typo in key manager
L.G.T.M
https://docs1.stg.tizen.org/staging/2021/application/native/api/common/8.0/

**Comment by sgchoi5** [comment]
Fixed additional typo in sst
L.G.T.M
https://docs1.stg.tizen.org/staging/2021/application/native/api/common/8.0/

**Comment by sgchoi5** [comment]
Removed unapproved functions in Machine Learning.
LGTM
https://docs1.stg.tizen.org/staging/2021/application/native/api/common/8.0/

**Review by safir-srbd — APPROVED** [review]
@sgchoi5 LGTM

**Pull request merged**
