### PR TITLE
Updated what is Tizen

### PR DESCRIPTION
**Pull request by omar-srbd**
### Change Description ###

@asm-foysal @mijin85cho 
This PR contains changes that could not be implemented in PRs:

- #1593
- #1597 
- #1604 
- #1605 
- #1606 
- #1611 
- #1615
- #1616 

PR created by: omar.saeed@samsung.com

### CODE REVIEW

**Review by arisha-srbd — COMMENTED** [review]
@mijin85cho hello, hope you are doing well. We wanted to know if we should address the minor issues (eg: sentence case..) of the other contents under "Platform" in this PR or would it be better to address those under separate PRs.

**Comment by mijin85cho** [comment]
> @mijin85cho hello, hope you are doing well. We wanted to know if we should address the minor issues (eg: sentence case..) of the other contents under "Platform" in this PR or would it be better to address those under separate PRs.

Hello, @arisha-srbd I hope you're doing well, too.
It depends on the volume of the files. If you put too many files in a PR, both the author and the reviewer feel hard to handle it.

I don't know how many pages you will handle : If there are not so many pages, you can put those in this PR. If there are many pages in the volume hard to handle in a PR, you'd better to separated the PR.

**Comment by mijin85cho** [comment]
> We checked and seems like there are almost 90-100 pages under "Platform", so to address that many pages under one PR would be difficult as you said. So, under this PR, we will address the pages under the topic "What is Tizen" only.

I have a question. Are you going to add another page updates to this PR?
I mean, is this PR not prepared yet for the review?

**Tip :** In the right side of each PR, you'd see **Labels**.
If this PR is not done yet, you can attach "WIP" label.

WIP, "Working in progress" means the author is not done yet with the update,
so reviewers can wait until this label is removed by the author.

**Review by arisha-srbd — COMMENTED** [review]
> > We checked and seems like there are almost 90-100 pages under "Platform", so to address that many pages under one PR would be difficult as you said. So, under this PR, we will address the pages under the topic "What is Tizen" only.
> 
> I have a question. Are you going to add another page updates to this PR? I mean, is this PR not prepared yet for the review?
> 
> **Tip :** In the right side of each PR, you'd see **Labels**. If this PR is not done yet, you can attach "WIP" label.
> 
> WIP, "Working in progress" means the author is not done yet with the update, so reviewers can wait until this label is removed by the author.

Perfect! We will add the "WIP" label then. Thank you for the tip. :D

**Comment by omar-srbd** [comment]
I am closing this PR as I am facing an issue with the branch.
Will reopen a new PR.

**Pull request closed without merging**
