### PR TITLE
Update the binary image names

### PR DESCRIPTION
**Pull request by jsngyoon**
### Change Description ###

- Update the binary image names for RPI

### CODE REVIEW

**Review by arisha-srbd — COMMENTED** [review]
Hello @jsngyoon. Hope you are doing well. I saw that some changes have been done in this PR to update the image names only. I wanted to check with you if you want me to review the whole file or just the modified part. I will do accordingly. Thanks.

**Comment by jsngyoon** [comment]
Hello, @arisha-srbd, please review the modified part only. Thanks.

**Comment by journey2w** [comment]
@arisha-srbd
Please review this PR after releasing Tizen Studio 4.6.
Please check the modified part. The Tizen platform wants to update all docs under the `What is Tizen` menu ASAP.

**Comment by journey2w** [comment]
@arisha-srbd
Please review this PR after releasing Tizen Studio 4.6.
Please check the modified part. The Tizen platform wants to update all docs under the `What is Tizen` menu ASAP.

**Review by arisha-srbd — APPROVED** [review]
@jsngyoon hello! I reviewed the modified part and it looks good to me. 

@asm-foysal @mijin80lee I am approving this PR for merging.

**Pull request merged**
