### PR TITLE
Merge branch 'tizen_6.0_prepare' to release Tizen 6.0 documents

### PR DESCRIPTION
**Pull request by journey2w**
### Change Description ###

1. Merged tizen_6.0_prepare to publish Tizen 6.0 documentation.
2. Resolve merge conflict.

Reference: PR #1303

### CODE REVIEW

**Comment by mijin85cho** [comment]
Question. As the source branch is `journey2w:tizen_6.0_release`,
PRs merged into `tizen_6.0_release` today is not included at this PR.

Don't we need to also include the PRs merged into `tizen_6.0_release` today?

image

**Comment by journey2w** [comment]
> Question. As the source branch is `journey2w:tizen_6.0_release`,
> PRs merged into `tizen_6.0_release` today is not included at this PR.
> 
> Don't we need to also include the PRs merged into `tizen_6.0_release` today?
> 
> image

I knew  it so I was working.
There were too many conflict to merge two branches again so I just cherried-pick the remained commits.
I resolved all conflicts as well while cherry-picking them.

**Review by mijin85cho — APPROVED** [review]
I appreciate your effort.

**Comment by journey2w** [comment]
Merging and cherry-picking were done.

**Review by mijin85cho — APPROVED** [review]
Thanks for the update

**Pull request merged**
