### PR TITLE
NUI View guide (.NET) - TizenFX links fixed.

### PR DESCRIPTION
**Pull request by piotrekgorny**
### Change Description ###

- Fix broken TizenFX links (2 links) reported in  issue #1488

### CODE REVIEW

**Comment by annie-samsung** [comment]
@piotrekgorny, the first page where the link is broken is this, the earlier page that I pointed was incorrect.

https://docs.tizen.org/application/dotnet/guides/connectivity/iotcon/
IoTivity offers seamless device-to-device connectivity

**Comment by annie-samsung** [comment]
> @piotrekgorny, the first page where the link is broken is this, the earlier page that I pointed was incorrect.
> 
> https://docs.tizen.org/application/dotnet/guides/connectivity/iotcon/
> IoTivity offers seamless device-to-device connectivity

@piotrekgorny would you be fixing this page as well: https://docs.tizen.org/application/dotnet/guides/connectivity/iotcon/

**Comment by piotrekgorny** [comment]
> > @piotrekgorny, the first page where the link is broken is this, the earlier page that I pointed was incorrect.
> > https://docs.tizen.org/application/dotnet/guides/connectivity/iotcon/
> > IoTivity offers seamless device-to-device connectivity
> 
> @piotrekgorny would you be fixing this page as well: https://docs.tizen.org/application/dotnet/guides/connectivity/iotcon/

@annie-samsung No, this PR contains fixes only for NUI View guide

**Review by annie-samsung — APPROVED** [review]
Approving

**Pull request merged**
