### PR TITLE
Update 6.0 TV tcs to fix broken link

### PR DESCRIPTION
**Pull request by sgchoi5**
Fixed the broken link using source.tizen.org
Fixed the old link using developer.tizen.org

### CODE REVIEW

**Comment by annie-samsung** [comment]
In the PDF, revision history with current change needs to be updated?

image

**Comment by sgchoi5** [comment]
> In the PDF, revision history with current change needs to be updated?
> 
> image

Not need it at this time. just, quick fix for bad link

**Comment by sgchoi5** [comment]
@annie-samsung  @mijin85cho plz, review this PR. VD division asked us to update wrong/old link asap.

**Review by annie-samsung — APPROVED** [review]
ok approving

**Pull request merged**
