### PR TITLE
Update the description of tts_repeat function

### PR DESCRIPTION
**Pull request by sgchoi5**
* Changed the description of tts_repeat function.
* Target: 5.0 / 5.5 / 6.0 / 6.5 Native API Reference
* ACR-1680: https://code.sec.samsung.net/jira/browse/ACR-1680

### CODE REVIEW

**Comment by sgchoi5** [comment]
https://docs1.stg.tizen.org/staging/1589/application/native/api/mobile/5.0/group__CAPI__UIX__TTS__MODULE.html
https://docs1.stg.tizen.org/staging/1589/application/native/api/mobile/5.5/group__CAPI__UIX__TTS__MODULE.html
https://docs1.stg.tizen.org/staging/1589/application/native/api/mobile/6.0/group__CAPI__UIX__TTS__MODULE.html
https://docs1.stg.tizen.org/staging/1589/application/native/api/mobile/6.5/group__CAPI__UIX__TTS__MODULE.html
https://docs1.stg.tizen.org/staging/1589/application/native/api/wearable/5.0/group__CAPI__UIX__TTS__MODULE.html

**Comment by sgchoi5** [comment]
L.G.T.M

https://docs1.stg.tizen.org/staging/1589/application/native/api/mobile/5.0/group__CAPI__UIX__TTS__MODULE.html
https://docs1.stg.tizen.org/staging/1589/application/native/api/mobile/5.5/group__CAPI__UIX__TTS__MODULE.html
https://docs1.stg.tizen.org/staging/1589/application/native/api/mobile/6.0/group__CAPI__UIX__TTS__MODULE.html
https://docs1.stg.tizen.org/staging/1589/application/native/api/mobile/6.5/group__CAPI__UIX__TTS__MODULE.html

https://docs1.stg.tizen.org/staging/1589/application/native/api/wearable/5.0/group__CAPI__UIX__TTS__MODULE.html
https://docs1.stg.tizen.org/staging/1589/application/native/api/wearable/5.5/group__CAPI__UIX__TTS__MODULE.html
https://docs1.stg.tizen.org/staging/1589/application/native/api/wearable/6.0/group__CAPI__UIX__TTS__MODULE.html
https://docs1.stg.tizen.org/staging/1589/application/native/api/wearable/6.5/group__CAPI__UIX__TTS__MODULE.html

https://docs1.stg.tizen.org/staging/1589/application/native/api/iot-headed/5.0/group__CAPI__UIX__TTS__MODULE.html
https://docs1.stg.tizen.org/staging/1589/application/native/api/iot-headed/5.5/group__CAPI__UIX__TTS__MODULE.html
https://docs1.stg.tizen.org/staging/1589/application/native/api/iot-headed/6.0/group__CAPI__UIX__TTS__MODULE.html
https://docs1.stg.tizen.org/staging/1589/application/native/api/iot-headed/6.5/group__CAPI__UIX__TTS__MODULE.html

**Review by arisha-srbd — COMMENTED** [review]
@sgchoi5 hope you are doing well. We went through the PR and found some errors throughout all the files. The number of issues we found is quite substantial, would you like us to point everything out to you or do you want feedback on only the parts you modified?

**Comment by sgchoi5** [comment]
@arisha-srbd Hello, arisha
HTML files of Native API Reference are generated via source header files (more than 3,000 files) gathered from SDK image file + doxygen tool.  
To fix something in Native API Reference, 
First of all, needs to file maintainer of header files having issues.
A maintainer needs to update exact header file first, submit it to SDK image file, 
by me, regenerates Native API reference and replace html files to be updated.

Anyway, if you think.. some must be updated, let me know it.

**Comment by sgchoi5** [comment]
@arisha-srbd plz, review only modified.

**Review by arisha-srbd — APPROVED** [review]
The author asked us to review only the parts that were modified. We gave a check and didn't find any issues specifically on those parts. 

@sgchoi5 @asm-foysal @mijin85cho so we are approving this PR to be merged.

**Comment by sgchoi5** [comment]
@arisha-srbd thanks for your review.
@asm-foysal @mijin85cho plz, review & approve this PR

**Pull request merged**
