### PR TITLE
Remove Mobile - MapsView C# Sample application

### PR DESCRIPTION
**Pull request by sgchoi5**
- Removed Mobile - MapsView C# Sample application
- Removed Wearable - MapsView C# Sample application
- Removed Wearable - Systeminfo2 C# Sample application
- Not referred by any pages in docs.tizen.org

### CODE REVIEW

**Comment by sgchoi5** [comment]
LGTM. It is removed successfully.
https://docs1.stg.tizen.org/staging/1565/application/dotnet/samples/location/overview/

**Comment by sgchoi5** [comment]
https://docs1.stg.tizen.org/staging/1565/application/dotnet/samples/system/overview/

**Comment by annie-samsung** [comment]
@sagarkedari please check if there is any other references to these sample apps in the documentation.

**Comment by sgchoi5** [comment]
There is no references to removed samples!

**Review by sagarkedari — APPROVED** [review]
@annie-samsung , I don't see any changes required in this PR. The PR is approved from my end.

**Pull request merged**
