### PR TITLE
Mobile - 5.0 - Add links to examples

### PR DESCRIPTION
**Pull request by lslachciak**
Issue: https://github.com/Samsung/TAU/issues/199
Problem: No links to examples
Solution: Add links to examples on code.tizen.org

Signed-off-by: Lukasz Slachciak <l.slachciak@samsung.com>

### CODE REVIEW

**Comment by singa2000** [comment]
@mijin85cho 
I know that verification team needs to be verified before it is applied the developer.tizen.org.
Do you know the procedure?

**Comment by mijin85cho** [comment]
@singa2000 If you mean the PR review we have been doing with the "verification",
in case of **Web api file** update, we skip the English check from the SRI-B.

We only ask approval from the author's coworker.
So to merge this PR, I request a coworker of lslachciak to check the update and approve it.

**Comment by lslachciak** [comment]
PR is ready for review. @TomaszLukawskiSam could you review?

**Comment by lslachciak** [comment]
Sample link to staging doc:
https://docs.stg.tizen.org/staging/768/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_DropdownMenu.htm

**Comment by mijin85cho** [comment]
I'll upload the updated 5.0 web api when https://github.com/Samsung/tizen-docs/pull/772 is also merged.

**Comment by lslachciak** [comment]
OK, thank you.

**Pull request merged**
