### PR TITLE
Add posibility to open button example

### PR DESCRIPTION
**Pull request by lslachciak**
Added button example opening code.tizen.org example in new window

Signed-off-by: Lukasz Slachciak <l.slachciak@samsung.com>

### CODE REVIEW

**Comment by lslachciak** [comment]
image

**Comment by singa2000** [comment]
If launch to  "https://code.tizen.org/demos?path=1.0%2Fexamples%2Fmobile%2FUIComponents%2Fcomponents%2Fcontrols%2Fbutton%2Findex.html",  sample site is not opened immediately.
It displayed the blank page.

**Comment by lslachciak** [comment]
@singa2000 because of the yesterday's path change WATT needed to be updated with 
https://github.com/Samsung/WATT/pull/144
After updating code.tizen.org with latest WATT we will have it properly working.

**Comment by lslachciak** [comment]
Final look of this button is here:
https://docs.stg.tizen.org/staging/763/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Button.htm

**Comment by lslachciak** [comment]
I made tr this this button looking more like serach" button on documentation site

**Comment by singa2000** [comment]
The "try now!" link is not intuitive.
How about the "Use Example" or another somethings..
For example, https://material.angular.io/components/checkbox/examples

**Comment by lslachciak** [comment]
I needed to resign from CSS styling because tizen.org ignores all styles
Restore previous button with "use example" text

**Comment by lslachciak** [comment]
@TizenDocsBot is not updating content under https://docs.stg.tizen.org/staging/763/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Button.htm
even if new PR is send.

But new PR will look like this:
image

**Comment by mijin85cho** [comment]
Hello.

I tested this update on Tizen Developer **Staging** Site, and the result is below.

image

I guess we will have same view on Tizen Developer Site, also.

Would you please confirm this update again with this expected result?
If you confirm, I'll merge this PR and upload the latest web api files to Tizen Developer Site,
as this PR is created on master branch.

**Comment by lslachciak** [comment]
Thanks @mijin85cho for review. Now I see that example is available on tizen.org:
but it doesn't have so nice styling as on your screenshot:
https://docs.tizen.org/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Button.htm
image

Are we missing something?

**Comment by mijin85cho** [comment]
Hello, @lslachciak 
I took the screenshot from the Tizen Developer Site, https://developer.tizen.org/development/api-references/web-application?redirect=https://developer.tizen.org/dev-guide/5.0.0/org.tizen.web.apireference/html/ui_fw_api/Mobile_UIComponents/mobile_Button.htm.

For now we can check the api files from both on https://developer.tizen.org and https://docs.tizen.org/.
So may it caused confusion regarding the screenshot.

**Comment by lslachciak** [comment]
OK, thank you it is clear now for me.
I understand that documentation on https://developer.tizen.org is the official one?

**Comment by mijin85cho** [comment]
Yes, it is.

But please also refer that we are moving the focus to https://docs.tizen.org/ from https://developer.tizen.org.

**Comment by lslachciak** [comment]
OK, so looks like default styling for button tag could be improved on  https://docs.tizen.org/

**Pull request merged**
