### PR TITLE
Adding some photos and videos of wearable profile to tizen-docs

### PR DESCRIPTION
**Pull request by lslachciak**
[Problem] Lack of photos of profile wearable - it is hard for users to imagine how the elements look like.
[Solution] Adding some photos and videos to tizen-docs.

### CODE REVIEW

**Comment by huytaduc** [comment]
checkout the webpage https://docs.stg.tizen.org/staging/609

**Comment by mijin85cho** [comment]
At where are these images used? I can't see any Web API reference pages that use these newly added images.

**Comment by mijin85cho** [comment]
According to #610, new images & videos are added by this PR.

However I can't find where below are used. These are not required from #610.
For where these are added?
 - docs/application/web/api/5.0/images/IndexScrollBar.ogv
 - docs/application/web/api/5.0/images/MoreOptions.ogv
 - docs/application/web/api/5.0/images/SwipeList.png

**Comment by dorlinski** [comment]
I removed unnecessary files.

> According to #610, new images & videos are added by this PR.
> 
> However I can't find where below are used. These are not required from #610.
> For where these are added?
> 
> * docs/application/web/api/5.0/images/IndexScrollBar.ogv
> * docs/application/web/api/5.0/images/MoreOptions.ogv
> * docs/application/web/api/5.0/images/SwipeList.png

**Pull request merged**
