### PR TITLE
[NUI] Text and TableView guides code examples fixes

### PR DESCRIPTION
**Pull request by MathewP1**
### Change Description ###

 - Fixed wrong variable types in TableView guide - example wouldn't build
 - Changed PropertyValues in Text guide

### Bugs Fixed ###
 - Issue #1229

### CODE REVIEW

**Review by mijin85cho — APPROVED** [review]
Thanks for the update.

**Comment by mijin85cho** [comment]
Hello, @Seoyeon2Kim Would you please also check this update related with #1229?

**Comment by mijin85cho** [comment]
Reminder. 
Hello,  @Seoyeon2Kim
Would you please check this PR and leave your opinion as a comment?

**Review by Seoyeon2Kim — APPROVED** [review]
Looks good to me.
As for PropertyValue, the type should be String like this PR.
(Sorry for the late review)

**Comment by mijin85cho** [comment]
> Looks good to me.
> As for PropertyValue, the type should be String like this PR.
> (Sorry for the late review)

Thanks for the confirmation. I'll merge this PR.

**Pull request merged**
