### PR TITLE
Fix broken links on Data Control page

### PR DESCRIPTION
**Pull request by journey2w**
### Change Description ###

The links for TizenFX API Reference were xxx.l so I fixed the typo from xxx.l to xxx.html on Data Control page.

### CODE REVIEW

**Comment by huytaduc** [comment]
checkout the webpage https://docs.stg.tizen.org/staging/505

**Comment by journey2w** [comment]
https://docs.stg.tizen.org/staging/505/application/dotnet/guides/app-management/data-control is okay on my Chrome browser.

Please check your PC.

**Comment by nawab-samsung** [comment]
@journey2w 
I am using 
- Google Chrome
- Version 71.0.3578.98 (Official Build) (64-bit)

And when I scroll down to the **end** of the page, overlapping of content happens, rest everything seems to be fine.
Probable reason:  Actually, the frame of the main content is not auto adjusting when the mini ToC frame slides down

- If it is rendering properly in your web browser then all is well, but in all my browsers, it's having the rendering issue.  
chrome
chrome 2

.

**Comment by journey2w** [comment]
@nawab-samsung 
Overlap page will be fixed by server development team in SEV.

**Comment by mijin80lee** [comment]
TD Sync Completed.(link check)

**Pull request merged**
