### PR TITLE
Updating certificate-smartthings.md 

### PR DESCRIPTION
**Pull request by sabeena21**
### Change Description ###

Updated the document with new screenshots and content for RT IDE Certification as per the latest released version 2.0. 
Also made minor language edits.

### CODE REVIEW

**Comment by mijin85cho** [comment]
Hello, @kvbhat .

For the update of Tizen Studio document, please raise PRs from Tizen Studio teams,
not asking to create PRs to Document team instead.

For now sabeena21 raised a PR, and I'm asking you to review this PR.
As I can't assign you as a reviewer on system, please leave a comment when you approve this PR.

**Comment by kvbhat** [comment]
Hello @mijin85cho 
The changes looks good to me.
We are co-working with documentation team for this task. 

The changes here are mostly the screenshots that are updated similar to https://developer.tizen.org/development/iot-preview/getting-started-tizen/setting-up-smartthings-cloud that we had raised previously.

Thanks

**Comment by mijin85cho** [comment]
With kvbhat 's approval, I merge this PR.

**Comment by mijin80lee** [comment]
TD Sync Completed.

**Pull request merged**
