### PR TITLE
[Common] Fixes in web API reference

### PR DESCRIPTION
**Pull request by pkosko**
This is the same change set as in #787, but for 5.5 branch

* Added the description about shared directory structure in application module (requested by security team)
* Fixed raised errors in cordova modules
* Removed unnecessary trailing whitespaces (cleaned files) and added missing optional/nullable tags
* Fixed structure of full web idl sections (elements grouped by its type: typedef, dictionary, interfaces, callbacks)
* Fixed printing of deprecated enumerators (related to comment #731 (comment))
* Fixed links in few modules (added in few modules instead of just text)

### CODE REVIEW

**Comment by pkosko** [comment]
I added review fixes which were requested on #787

**Comment by journey2w** [comment]
@lbardeli and @djuszczakk 
You guys reviewed  PR #787. If you approved this PR, I will approve this PR and merge it.
You can't approve on the review menu. It is okay to remain comments for the approval.

**Comment by lbardeli** [comment]
@journey2w I reviewed and  approved this PR

**Comment by journey2w** [comment]
When I glanced at this PR, I could see a few grammatical mistakes. However,  I'm not a native and they are minor mistakes. I believe that the other reviewers reviewed the changes. So... I'll merge the PR.

**Pull request merged**
