### PR TITLE
[TV] Removed unneeded privileges from TV modules since 5.0

### PR DESCRIPTION
**Pull request by pkosko**
TV API does not need any privilege on native level, thus for consistency,
  privileges are also not needed on web level.

[ACR] http://suprem.sec.samsung.net/jira/browse/TWDAPI-198

### CODE REVIEW

**Comment by huytaduc** [comment]
checkout the webpage https://docs.stg.tizen.org/staging/528

**Comment by huytaduc** [comment]
checkout the webpage https://docs.stg.tizen.org/staging/528

**Comment by huytaduc** [comment]
checkout the webpage https://docs.stg.tizen.org/staging/528

**Comment by huytaduc** [comment]
checkout the webpage https://docs.stg.tizen.org/staging/528

**Comment by pkosko** [comment]
https://github.com/Samsung/tizen-docs/pull/518 - related pull request. Adds deprecation information in file docs/application/web/tutorials/sec-privileges.md. To avoid conflicts I didn't add this information again.

**Comment by huytaduc** [comment]
checkout the webpage https://docs.stg.tizen.org/staging/528

**Pull request closed without merging**
