### PR TITLE
Replace vs platform version screenshot

### PR DESCRIPTION
**Pull request by mihashco**
### Change Description ###

Tizen profile configuration popup uses ElmShapr. For dotnet platform NUI template is common type. This PR change metioned config screenshot

### CODE REVIEW

**Review by omar-srbd — COMMENTED** [review]
@mihashco, I hope you're doing well.
I have checked the change you made on the .PNG file in this PR. I have a concern regarding the change,
"https://docs.tizen.org/application/vstools/Tizen/dotnet/" uses the .PNG file that you have changed. It has come to my notice that all the following images (_dotnet_build_project.PNG_, _dotnet_run_application1.PNG_, _dotnet_run_application2.PNG_, _dotnet_debug_application.PNG_) on this page have the template name "**ElmSharpTemplate1**".

My concern is, shouldn't all the following images also have a similar template name? As in "**TizenNUIApp**"?

**Comment by mijin85cho** [comment]
> @mijin85cho Hello. Hope you are well.
> 
> I believe the image that @mihashco is trying to change is part of `vstools/dotnet.md`, a file that has been removed in #1627, and the content of which has been merged with `dotnet/get-started/first-app.md`. In this case, how should this be handled?

Hello, @omar-srbd 

As you said, the image `dotnet_platform_version_new.PNG` was used in `vstools/Tizen/dotnet.md`, the removed page.
So updating `dotnet_platform_version_new.PNG` is meaningless.

(To prevent this kind of confusion we recommend to delete the unused images during the update.)


The page was merged into `dotnet/get-started/first-app.md`, so the image used in `dotnet/get-started/first-app.md` should be checked instead.
In the content, I think the corresponding image of `dotnet_platform_version_new.PNG` is `vs2022_project_create_4.png` in the master branch.

Also, @asm-foysal 
The PR #1627 does not seems to be applied to docs.tizen.org yet. Would you please sync the master to live branch?

**Review by safir-srbd — COMMENTED** [review]
@mijin85cho Thank you for providing feedback on @omar-srbd's concern. 
We will be syncing master to live now.

**Comment by asm-foysal** [comment]
@mijin85cho hello!
Any suggestion on how we deal with this PR?

**Comment by mijin85cho** [comment]
> @mijin85cho hello! Any suggestion on how we deal with this PR?

Hello, @asm-foysal 
About the image update, as [my above comment](https://github.com/Samsung/tizen-docs/pull/1660#issuecomment-1200622829), the valid latest image should be checked instead of unused old image.

So we should guide @mihashco to check the latest status of the page again.

**Comment by mihashco** [comment]
Hello. Thank you for checking and sorry for late reply. It looks like documentation hosted on page and github master branch is different. If mentioned image is not used any more in the docs. I can close this pull request.

**Comment by mijin85cho** [comment]
> Hello. Thank you for checking and sorry for late reply. It looks like documentation hosted on page and github master branch is different. If mentioned image is not used any more in the docs. I can close this pull request.

Hello. For now the master branch and the docs.tizen.org are synced, so you can check on https://docs.tizen.org/application/dotnet/get-started/first-app/. Would you please check the updated page and close this PR if you think the updated version is proper?

**Comment by mihashco** [comment]
Outdated: following picture is not used anymore

**Pull request closed without merging**
