### PR TITLE
Update tizen studio RT docs for 3.0

### PR DESCRIPTION
**Pull request by vivek-ellur**
Signed-off-by: vivek ellur <vivek.ellur@samsung.com>

### Change Description ###

Describe your changes here.

For instance,
 - Fix broken links of native application docs.
 -  ...

### Bugs Fixed ###

Provide links to bugs here

For instance,

 - Issue #265

### API Changes ###

In case of ACR, put the link of ACR

For instance,

 - ACR: ACR-1120

### CODE REVIEW

**Comment by mijin85cho** [comment]
Hello,
I assigned @surbhig12 to this PR instead of @annie-samsung, as @annie-samsung is absent for now.

@surbhig12, please assign a reviewer to this PR.

**Comment by mijin85cho** [comment]
Thanks for the review, @sabeena21.

Just two questions.

At where are these images used?
 - ellipse.png
 - open_a_terminal.png
 - rt_build_dropdown_menu.png

It looks like some personal information are shown on the images. Is it ok?
(bd1978/git/tinyara-new)

**Comment by vivek-ellur** [comment]
1) ellipse.png and open_a_terminal.png have been removed.
rt_build_dropdown_menu.png is being used in smartthings-ext/build-smartthings.md file.
2) I think it is ok..because those images were being used in previous version also.

**Comment by mijin85cho** [comment]
About rt_build_dropdown_menu.png.
The rt_build_dropdown_menu.png in use is under `rt-ide/smartthings-ext/media/`,
but we have one another rt_build_dropdown_menu.png file under `rt-ide/getting-started/media/`.

In your PR, `rt-ide/getting-started/media/rt_build_dropdown_menu.png` is updated, 
and I'm not sure if this update is valid as I can't find from where `rt-ide/getting-started/media/rt_build_dropdown_menu.png` is used.
Would you please check?

**Comment by huytaduc** [comment]
checkout the webpage https://docs.stg.tizen.org/staging/429

**Comment by huytaduc** [comment]
checkout the webpage https://docs.stg.tizen.org/staging/429

**Comment by vivek-ellur** [comment]
Removed rt_build_dropdown_menu.png image from rt-ide/getting-started/media/ and updated the image in rt-ide/smartthings-ext/media/

**Comment by mijin85cho** [comment]
Thanks for the update.
@sabeena21, would you please approve again?
I'll merge with your approval.

**Comment by mijin80lee** [comment]
TD Sync Completed.

**Pull request merged**
