### PR TITLE
[NUI] Modify get-started page

### PR DESCRIPTION
**Pull request by journey2w**
I won't merge this PR. The aim of this PR shows how to change NUI XAML pages created by the XAML module owner.

### CODE REVIEW

**Comment by dongsug-song** [comment]
Hello, I am very sorry. here are too many fixes and too many comments.
I made a new PR again. please check this : #1007.
I will close this.
Thank you.

**Comment by mijin85cho** [comment]
> Hello, I am very sorry. here are too many fixes and too many comments.
> I made a new PR again. please check this : #1007.
> I will close this.
> Thank you.

Instead of @dongsug-song, I close this PR.

**Comment by journey2w** [comment]
I will reopen this PR. I told you I would close this PR.
I hoped the author to see my changes.

**Comment by journey2w** [comment]
I confirmed that PR #1007 updated the requested changes.

**Pull request closed without merging**
