### PR TITLE
[7.0][Web API] Fix spelling mistakes in notifications API 

### PR DESCRIPTION
**Pull request by m-bialek**
### Change Description ###

- fix spelling mistakes (missing articles, missing commas, etc.)

### Bugs Fixed ###

N/A

### API Changes ###

N/A

### CODE REVIEW

**Review by omar-srbd — COMMENTED** [review]
Hello @m-bialek, I hope you are doing well.
I can see that this PR is related to PR https://github.com/Samsung/tizen-docs/pull/1601. At the same time, some of the changes that I have suggested in the comments of PR https://github.com/Samsung/tizen-docs/pull/1601 have been implemented here. Could you please tell me if there is any significance on why this PR has been opened?
Thank you.

**Review by omar-srbd — COMMENTED** [review]
@m-bialek,
Please combine https://github.com/Samsung/tizen-docs/pull/1601 and this PR (https://github.com/Samsung/tizen-docs/pull/1622). Also, please implement all the suggested changes on https://github.com/Samsung/tizen-docs/pull/1601. Any further discussion/changes will be continued on https://github.com/Samsung/tizen-docs/pull/1601.

**Comment by m-bialek** [comment]
Though I cannot combine them. #1601 refers to the specific ACR which does not include changes introduced by this PR. Therefore, those PRs have to be separated. I would like to implement all your suggestions, but HTMLs are generated automatically and I can control only a part of the final result. To apply all the suggestions I would have to modify the templates which I am not supposed to.

**Review by omar-srbd — COMMENTED** [review]
@m-bialek Hi,
It came to my notice that the left navigation bar (LNB) is not visible on the staging site of the HTML files in this PR. Is there any specific reason for it?

**Comment by mijin85cho** [comment]
> @m-bialek Hi, It came to my notice that the left navigation bar (LNB) is not visible on the staging site of the HTML files in this PR. Is there any specific reason for it?

Hello, @omar-srbd 
It is related with /application/web/api/toc.xml.

As like the /application/toc_all.md for Guide / Get Started / Tools and etc,
API files also need a toc file to manage the LNB for APIs

If you check /application/web/api/toc.xml, you'd see it is listing up every Native & Web API menu tree for every Tizen version till Tizen 6.5, the last latest public version. 
(So the file is really big.)

Thus, just check the content of this PR, not considering LNB. It is a different issue and not related with this PR.
I guess you can find the URLs for this PR, 
https://docs1.stg.tizen.org/staging/1622/application/web/api/7.0/device_api/mobile/tizen/notification.html for mobile and https://docs1.stg.tizen.org/staging/1622/application/web/api/7.0/device_api/wearable/tizen/notification.html for wearable.

**Reference :** Tizen 6.5 was added to the LNB for APIs with  https://github.com/Samsung/tizen-docs/commit/2d74582547163b66228f7c1e6853bce2a2b11362.

**Comment by mijin85cho** [comment]
Hello, @asm-foysal

It seems this PR is not approved yet from SRBD reviewers. Did you had chat with @omar-srbd about merging this PR?

**Review by asm-foysal — COMMENTED** [review]
@mijin85cho hope you are doing well.
Yes, I had a chat with Omar before merging this PR.

**Comment by mijin85cho** [comment]
> @mijin85cho hope you are doing well. Yes, I had a chat with Omar before merging this PR.

I see. Thanks for confirming.
To prevent the confusion between members as like [my previous comment](https://github.com/Samsung/tizen-docs/pull/1622#issuecomment-1097731231), please leave the traces on github.
When you merge the PRs, please check if they are 'approved'.

**Pull request merged**
