### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by tyoungroy**
Signed-off-by: Tae-Young Chung <ty83.chung@samsung.com>

### Change Description ###

Fix typos native application docs.

### CODE REVIEW

**Comment by huytaduc** [comment]
checkout the webpage https://docs.stg.tizen.org/staging/533

**Comment by mijin85cho** [comment]
Hello.
Native api files in this repository are just for back up.

This tizen-docs repository is not used for generating Native API files, 
so fixing the files here is meaningless.

To fix the Native API files, please ask to sunggyu.choi.

**Comment by mijin85cho** [comment]
Hello, @tyoungroy.
Would you please check my above comment and close this PR?

**Comment by mijin85cho** [comment]
Closing this PR as it is not on correct repository to fix the typo issue.

**Pull request closed without merging**
