### PR TITLE
Dev remove toc file

### PR DESCRIPTION
**Pull request by rikaki20111492**
### Change Description ###

Describe your changes here.

For instance,
 - Fix broken links of native application docs.
 -  ...

### Bugs Fixed ###

Provide links to bugs here

For instance,

 - Issue #265

### API Changes ###

In case of ACR, put the link of ACR

For instance,

 - ACR: ACR-1120

### CODE REVIEW

**Comment by huytaduc** [comment]
checkout the webpage https://docs.stg.tizen.org/staging/471

**Comment by huytaduc** [comment]
checkout the webpage https://docs.stg.tizen.org/staging/471

**Comment by huytaduc** [comment]
checkout the webpage https://docs.stg.tizen.org/staging/471

**Comment by huytaduc** [comment]
checkout the webpage https://docs.stg.tizen.org/staging/471

**Comment by huytaduc** [comment]
checkout the webpage https://docs.stg.tizen.org/staging/471

**Comment by huytaduc** [comment]
checkout the webpage https://docs.stg.tizen.org/staging/471

**Comment by huytaduc** [comment]
checkout the webpage https://docs.stg.tizen.org/staging/471

**Comment by huytaduc** [comment]
checkout the webpage https://docs.stg.tizen.org/staging/471

**Comment by journey2w** [comment]
@rikaki20111492
I'd like to close this PR because you seems to finish testing this PR.
I didn't remove pull_463 branch so you can reopen this PR and get the latest commit on pull_463 branch anytime you want.
Thanks.

**Pull request closed without merging**
