### PR TITLE
[ACR-1714][voice-control] Add TIDL privileges in VCE prerequisites

### PR DESCRIPTION
**Pull request by syeonholic**
### API Changes ###

 - ACR: ACR-1714
 - Add TIDL privileges in VCE prerequisites
 - https://jira.sec.samsung.net/browse/ACR-1714

### CODE REVIEW

**Review by urmain — APPROVED** [review]
LGTM~!!!!

**Review by psw0405 — APPROVED** [review]
LGTM

**Review by stom-hwang — APPROVED** [review]
LGTM 👍

**Comment by journey2w** [comment]
Just for testing  TizenDocsBot  comment

**Review by safir-srbd — APPROVED** [review]
@syeonholic Hello. Hope you are doing well.

I have gone through the PR and everything looks good to me. I am approving this PR for merging.

**Pull request merged**
