### PR TITLE
Fix wrong expression of attach-panel guide.

### PR DESCRIPTION
**Pull request by hallower**
Dear @Reni-90 

I fixed wrong expressions that indicated in here(https://github.com/Samsung/tizen-docs/pull/226)
Please review this modification.
Thank you.

Signed-off-by: cskim <charles0.kim@samsung.com>

### CODE REVIEW

**Comment by Reni-90** [comment]
@hallower 
Thank you. Reviewed the modification.

**Comment by Reni-90** [comment]
The mentioned modification is updated properly. Please take the modified file from #226 and make the modification. The current file is not the modified file.

**Comment by Reni-90** [comment]
I am sorry. My intension was not to merge the files into master. 
#226 is the reviewed and updated document, which has enumerator instead of enumeration. I requested to change enumerator to enumeration.
The change was made correctly but in an older file (which does not have the sentence rephrasing and changes).  
Any questions, please feel free to ask.

**Comment by hallower** [comment]
Ok, 
I will make a same PR for the tizen_5.0_prepare branch.

**Comment by hallower** [comment]
Please review this PR.

**Pull request closed without merging**
