### PR TITLE
Change up-to-date screenshots for vstools

### PR DESCRIPTION
**Pull request by journey2w**
### Change Description ###

Change up-to-date screenshots for vstools.

### CODE REVIEW

**Comment by mijin85cho** [comment]
Question. In this diff, I can see the `howtoinstall-extensionwindows.png` and `cps-extension-and-updates.png` images are replaced with `cps-extensions-and-updates.png`.

`cps-extension-and-updates.png` image is removed, but `howtoinstall-extensionwindows.png` remains.
How about removing `howtoinstall-extensionwindows.png` also?

**Comment by journey2w** [comment]
Question. In this diff, I can see the howtoinstall-extensionwindows.png and cps-extension-and-updates.png images are replaced with cps-extensions-and-updates.png.

cps-extension-and-updates.png image is removed, but howtoinstall-extensionwindows.png remains.
How about removing howtoinstall-extensionwindows.png also?

-> There is no reason to use different screenshots. 
I will delete howtoinstall-extensionwindows.png because it is not used anymore.

**Comment by mijin85cho** [comment]
Hello. I found another issue related with this page.

There are two places, using image `cs_prerequisite01-250x401.png`.
However it looks like the second `cs_prerequisite01-250x401.png` should be `cs_prerequisite-disable-hiperv.png` according to the text.
Would you please check?

**The image on Github**

---

image

**The image on TD**

---

image

**Comment by journey2w** [comment]
> Hello. I found another issue related with this page.
> 
> There are two places, using image `cs_prerequisite01-250x401.png`.
> However it looks like the second `cs_prerequisite01-250x401.png` should be `cs_prerequisite-disable-hiperv.png` according to the text.
> Would you please check?
> 
> **The image on Github**
> 
> image
> 
> **The image on TD**
> 
> image

Fixed.

**Pull request merged**
