### PR TITLE
One UI image updates P4  || For 1263

### PR DESCRIPTION
**Pull request by nawab-samsung**
#1246 
`docs/application/dotnet/tutorials/media/testing_your_app_on_gear1.png`
`docs/application/dotnet/tutorials/media/testing_your_app_on_gear2.png`
`docs/application/dotnet/tutorials/media/testing_your_app_on_gear3.png`

#1247 
`docs/application/dotnet/tutorials/media/testing_your_app_on_gear4.png`
`docs/application/dotnet/tutorials/media/testing_your_app_on_gear6.png`
`docs/application/dotnet/tutorials/media/testing_your_app_on_gear7.png`

This PR
`docs/application/dotnet/tutorials/media/testing_your_app_on_gear5.png`

### CODE REVIEW

**Comment by mijin85cho** [comment]
Suggestion. 

Please git add `docs/application/dotnet/tutorials/media/testing_your_app_on_gear4.png`, `docs/application/dotnet/tutorials/media/testing_your_app_on_gear6.png`, and `docs/application/dotnet/tutorials/media/testing_your_app_on_gear7.png`.

As https://github.com/Samsung/tizen-docs/pull/1247 update is tangled, and other files are updated with #1264, 
it would be more efficient to close #1247.

I recommend to
 - close #1247, and 
 - update the dotnet images of #1247 at here, #1265.

So the status of the images I want for #1265 is :
`docs/application/dotnet/tutorials/media/testing_your_app_on_gear4.png`
`docs/application/dotnet/tutorials/media/testing_your_app_on_gear5.png`
`docs/application/dotnet/tutorials/media/testing_your_app_on_gear6.png`
`docs/application/dotnet/tutorials/media/testing_your_app_on_gear7.png`

**Comment by nawab-samsung** [comment]
Sure @mijin85cho will process as per your directions. 
Thanks

**Comment by nawab-samsung** [comment]
@mijin85cho current status of this PR is as per your suggestion: 
docs/application/dotnet/tutorials/media/testing_your_app_on_gear4.png
docs/application/dotnet/tutorials/media/testing_your_app_on_gear5.png
docs/application/dotnet/tutorials/media/testing_your_app_on_gear6.png
docs/application/dotnet/tutorials/media/testing_your_app_on_gear7.png

Kindly let me know if anything is incorrect.

**Review by mijin85cho — APPROVED** [review]
Thanks for the update.

**Pull request merged**
